#!/usr/bin/env python3
"""Generate llrpkit's protocol modules from LLRP definition XML files.

Inputs
------
* ``codegen/llrpdef.xml`` — core LLRP 1.0.1 definitions (LLRP Toolkit,
  Apache-2.0; see ``codegen/THIRD_PARTY.md``).
* ``codegen/impinj.xml`` — llrpkit's own definition of the Impinj Octane
  LLRP vendor extensions (PEN 25882).

Outputs (committed to the repository)
-------------------------------------
* ``src/llrpkit/protocol/enums.py``
* ``src/llrpkit/protocol/params.py``
* ``src/llrpkit/protocol/messages.py``
* ``src/llrpkit/protocol/impinj.py``

The generator is deterministic: same inputs, byte-identical outputs. CI runs
``generate.py --check`` to prove the committed modules match the definitions.
"""

from __future__ import annotations

import argparse
import keyword
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT_DIR = ROOT.parent / "src" / "llrpkit" / "protocol"
CORE_XML = ROOT / "llrpdef.xml"
IMPINJ_XML = ROOT / "impinj.xml"

# Handled structurally by the codec, not generated.
SKIP_DEFS = {"Custom", "CUSTOM_MESSAGE"}

# Field types whose decoded value is converted to an enum member when the
# definition names an enumeration (vectors keep raw ints).
SCALAR_ENUM_TYPES = {"u2", "u8", "s8", "u16", "s16", "u32", "s32", "u64", "s64"}

HEADER = (
    '"""{title}\n'
    "\n"
    "Generated by ``codegen/generate.py`` from ``codegen/{source}`` — do not edit\n"
    "by hand. Edit the definitions or the generator and regenerate.\n"
    '"""\n'
    "\n"
    "# ruff: noqa: E501, F401, I001, N801, N815, RUF100\n"
    "from __future__ import annotations\n"
)


# ---------------------------------------------------------------------------
# Intermediate representation
# ---------------------------------------------------------------------------


@dataclass
class FieldDef:
    name: str
    ftype: str
    enum: str | None


@dataclass
class ReservedDef:
    bits: int


@dataclass
class RefDef:
    type_name: str
    repeat: str  # "1", "0-1", "0-N", "1-N"

    @property
    def is_list(self) -> bool:
        return self.repeat.endswith("N")

    @property
    def min_count(self) -> int:
        return 1 if self.repeat.startswith("1") else 0


@dataclass
class StructDef:
    kind: str  # "parameter" | "message"
    name: str
    type_num: int | None  # standard type number (None for custom)
    subtype: int | None  # custom subtype (None for standard)
    items: list[FieldDef | ReservedDef | RefDef] = field(default_factory=list)

    @property
    def is_custom(self) -> bool:
        return self.subtype is not None

    @property
    def is_tv(self) -> bool:
        return self.kind == "parameter" and self.type_num is not None and self.type_num < 128

    @property
    def fields(self) -> list[FieldDef | ReservedDef]:
        return [i for i in self.items if isinstance(i, FieldDef | ReservedDef)]

    @property
    def refs(self) -> list[RefDef]:
        return [i for i in self.items if isinstance(i, RefDef)]


@dataclass
class EnumDef:
    name: str
    entries: list[tuple[str, int]]


@dataclass
class Model:
    core_params: list[StructDef] = field(default_factory=list)
    core_messages: list[StructDef] = field(default_factory=list)
    core_enums: list[EnumDef] = field(default_factory=list)
    choices: dict[str, list[str]] = field(default_factory=dict)
    vendor_id: int = 0
    vendor_params: list[StructDef] = field(default_factory=list)
    vendor_messages: list[StructDef] = field(default_factory=list)
    vendor_enums: list[EnumDef] = field(default_factory=list)

    def struct_names(self) -> dict[str, str]:
        """Map struct name -> owning module ('params' | 'impinj')."""
        names: dict[str, str] = {}
        for s in self.core_params:
            names[s.name] = "params"
        for s in self.vendor_params:
            names[s.name] = "impinj"
        return names


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def _parse_items(defn: ET.Element) -> list[FieldDef | ReservedDef | RefDef]:
    items: list[FieldDef | ReservedDef | RefDef] = []
    for el in defn:
        tag = _local(el.tag)
        if tag == "field":
            ftype = el.get("type")
            name = el.get("name")
            if not ftype or not name:
                raise SystemExit(f"field without type/name in {defn.get('name')}")
            items.append(FieldDef(name, ftype, el.get("enumeration")))
        elif tag == "reserved":
            items.append(ReservedDef(int(el.get("bitCount", "0"))))
        elif tag in ("parameter", "choice"):
            tname = el.get("type")
            if not tname:
                raise SystemExit(f"ref without type in {defn.get('name')}")
            items.append(RefDef(tname, el.get("repeat", "1")))
        # annotations and anything else are ignored
    return items


def _parse_enum(defn: ET.Element) -> EnumDef:
    entries: list[tuple[str, int]] = []
    for el in defn:
        if _local(el.tag) == "entry":
            name = el.get("name")
            value = el.get("value")
            if name is None or value is None:
                raise SystemExit(f"bad enum entry in {defn.get('name')}")
            entries.append((name, int(value)))
    ename = defn.get("name")
    if ename is None:
        raise SystemExit("enumeration without a name")
    return EnumDef(ename, entries)


def parse_core(path: Path, model: Model) -> None:
    root = ET.parse(path).getroot()
    for defn in root:
        tag = _local(defn.tag)
        name = defn.get("name", "")
        if name in SKIP_DEFS:
            continue
        if tag == "parameterDefinition":
            s = StructDef(
                "parameter", name, int(defn.get("typeNum", "0")), None, _parse_items(defn)
            )
            if s.is_tv and s.refs:
                raise SystemExit(f"TV parameter {name} unexpectedly has sub-parameters")
            model.core_params.append(s)
        elif tag == "messageDefinition":
            model.core_messages.append(
                StructDef("message", name, int(defn.get("typeNum", "0")), None, _parse_items(defn))
            )
        elif tag == "enumerationDefinition":
            model.core_enums.append(_parse_enum(defn))
        elif tag == "choiceDefinition":
            members = [el.get("type", "") for el in defn if _local(el.tag) == "parameter"]
            model.choices[name] = [m for m in members if m]


def parse_vendor(path: Path, model: Model) -> None:
    root = ET.parse(path).getroot()
    for defn in root:
        tag = _local(defn.tag)
        name = defn.get("name", "")
        if tag == "vendorDefinition":
            model.vendor_id = int(defn.get("vendorID", "0"))
        elif tag == "customParameterDefinition":
            model.vendor_params.append(
                StructDef(
                    "parameter", name, None, int(defn.get("subtype", "0")), _parse_items(defn)
                )
            )
        elif tag == "customMessageDefinition":
            model.vendor_messages.append(
                StructDef("message", name, None, int(defn.get("subtype", "0")), _parse_items(defn))
            )
        elif tag in ("enumerationDefinition", "customEnumerationDefinition"):
            model.vendor_enums.append(_parse_enum(defn))


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------


def snake(name: str) -> str:
    n = name.replace("-", "_")
    n = n.replace("IDs", "Ids").replace("ID", "Id")
    n = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", n)
    n = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", n)
    n = re.sub(r"__+", "_", n).lower()
    if keyword.iskeyword(n):
        n += "_"
    return n


def enum_member(name: str) -> str:
    n = re.sub(r"\W", "_", name)
    if n[0].isdigit():
        n = "V_" + n
    if keyword.iskeyword(n):
        n += "_"
    return n


def class_name(name: str) -> str:
    return name.replace("-", "_")


# ---------------------------------------------------------------------------
# Field type mapping
# ---------------------------------------------------------------------------


@dataclass
class FType:
    ann: str
    default: str
    enc: str  # format with {a} = attribute name
    dec: str


FIELD_TYPES: dict[str, FType] = {
    "u1": FType("bool", "False", "w.bits(int(self.{a}), 1)", "bool(r.bits(1))"),
    "u2": FType("int", "0", "w.bits(self.{a}, 2)", "r.bits(2)"),
    "u8": FType("int", "0", "w.u8(self.{a})", "r.u8()"),
    "s8": FType("int", "0", "w.s8(self.{a})", "r.s8()"),
    "u16": FType("int", "0", "w.u16(self.{a})", "r.u16()"),
    "s16": FType("int", "0", "w.s16(self.{a})", "r.s16()"),
    "u32": FType("int", "0", "w.u32(self.{a})", "r.u32()"),
    "s32": FType("int", "0", "w.s32(self.{a})", "r.s32()"),
    "u64": FType("int", "0", "w.u64(self.{a})", "r.u64()"),
    "s64": FType("int", "0", "w.s64(self.{a})", "r.s64()"),
    "u96": FType("bytes", 'b"\\x00" * 12', "w.u96(self.{a})", "r.u96()"),
    "u1v": FType("BitStr", "field(default_factory=BitStr)", "w.u1v(self.{a})", "r.u1v()"),
    "u8v": FType("bytes", 'b""', "w.u8v(self.{a})", "r.u8v()"),
    "u16v": FType("list[int]", "field(default_factory=list)", "w.u16v(self.{a})", "r.u16v()"),
    "u32v": FType("list[int]", "field(default_factory=list)", "w.u32v(self.{a})", "r.u32v()"),
    "utf8v": FType("str", '""', "w.utf8v(self.{a})", "r.utf8v()"),
    "bytesToEnd": FType("bytes", 'b""', "w.raw(self.{a})", "r.read_to(end)"),
}


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------


@dataclass
class EmitCtx:
    model: Model
    module: str  # "params" | "messages" | "impinj"

    def struct_ref(self, name: str) -> str:
        owner = self.model.struct_names().get(name)
        if owner is None:
            raise SystemExit(f"unresolved parameter reference: {name}")
        return name if owner == self.module else f"params.{name}"

    def enum_ref(self, name: str) -> str:
        if any(e.name == name for e in self.model.vendor_enums):
            return name if self.module == "impinj" else f"impinj.{name}"
        if any(e.name == name for e in self.model.core_enums):
            return name if self.module == "enums" else f"enums.{name}"
        raise SystemExit(f"unresolved enumeration reference: {name}")

    def ref_classes(self, ref: RefDef) -> list[str]:
        if ref.type_name == "Custom":
            return ["CustomParameter"]
        members = self.model.choices.get(ref.type_name)
        if members is None:
            return [self.struct_ref(class_name(ref.type_name))]
        out: list[str] = []
        for m in members:
            out.append("CustomParameter" if m == "Custom" else self.struct_ref(class_name(m)))
        return out


@dataclass
class Slot:
    attr: str
    classes: list[str]
    min_count: int
    is_list: bool


def struct_slots(s: StructDef, ctx: EmitCtx) -> list[Slot]:
    slots: list[Slot] = []
    used = {snake(f.name) for f in s.items if isinstance(f, FieldDef)}
    for ref in s.refs:
        if ref.type_name == "Custom":
            attr = "custom"
        else:
            attr = snake(ref.type_name)
            if ref.is_list and not attr.endswith("s"):
                attr += "s"
        base_attr = attr
        n = 2
        while attr in used:
            attr = f"{base_attr}_{n}"
            n += 1
        used.add(attr)
        slots.append(Slot(attr, ctx.ref_classes(ref), ref.min_count, ref.is_list))
    # Custom parameters are ambiguous on the wire: a choice that admits Custom
    # would otherwise capture vendor extensions destined for the container's
    # plain `custom` slot. When both exist, the plain slot wins and the choice
    # binds only its concrete members.
    if any(s2.attr == "custom" for s2 in slots):
        for s2 in slots:
            if s2.attr != "custom" and len(s2.classes) > 1:
                s2.classes = [c for c in s2.classes if c != "CustomParameter"]
    return slots


def emit_enum_class(e: EnumDef) -> list[str]:
    lines = [f"class {e.name}(IntEnum):", f'    """LLRP enumeration ``{e.name}``."""', ""]
    for name, value in e.entries:
        lines.append(f"    {enum_member(name)} = {value}")
    lines.append("")
    lines.append("")
    return lines


def emit_struct(s: StructDef, ctx: EmitCtx, vendor_id: int = 0) -> list[str]:
    cname = class_name(s.name)
    lines: list[str] = []
    if s.kind == "parameter":
        register = "@register_parameter"
        base = "CustomParameter" if s.is_custom else "LLRPParameter"
    else:
        register = "@register_message"
        base = "CustomMessage" if s.is_custom else "LLRPMessage"
    lines.append(register)
    lines.append("@dataclass(kw_only=True)")
    lines.append(f"class {cname}({base}):")
    if s.is_custom:
        what = "custom parameter" if s.kind == "parameter" else "custom message"
        lines.append(f'    """``{s.name}`` — vendor {what}, subtype {s.subtype}."""')
        lines.append("")
        lines.append(f"    VENDOR_ID: ClassVar[int] = {vendor_id}")
        lines.append(f"    SUBTYPE: ClassVar[int] = {s.subtype}")
    elif s.kind == "parameter":
        kind = "TV parameter" if s.is_tv else "TLV parameter"
        lines.append(f'    """``{s.name}`` — LLRP {kind}, type {s.type_num}."""')
        lines.append("")
        lines.append(f"    PARAM_TYPE: ClassVar[int] = {s.type_num}")
        if s.is_tv:
            lines.append("    IS_TV: ClassVar[bool] = True")
    else:
        lines.append(f'    """``{s.name}`` — LLRP message, type {s.type_num}."""')
        lines.append("")
        lines.append(f"    MESSAGE_TYPE: ClassVar[int] = {s.type_num}")

    slots = struct_slots(s, ctx)

    body_lines: list[str] = []
    for item in s.items:
        if not isinstance(item, FieldDef):
            continue
        ft = FIELD_TYPES.get(item.ftype)
        if ft is None:
            raise SystemExit(f"unhandled field type {item.ftype!r} in {s.name}")
        attr = snake(item.name)
        comment = f"  # enum: {item.enum}" if item.enum else ""
        body_lines.append(f"    {attr}: {ft.ann} = {ft.default}{comment}")
    for slot in slots:
        union = " | ".join(slot.classes)
        if slot.is_list:
            body_lines.append(f"    {slot.attr}: list[{union}] = field(default_factory=list)")
        elif slot.min_count:
            body_lines.append(f"    {slot.attr}: {union}")
        else:
            body_lines.append(f"    {slot.attr}: {union} | None = None")
    if body_lines:
        lines.append("")
        lines.extend(body_lines)

    if s.fields:
        lines.append("")
        lines.append("    def _encode_fields(self, w: ByteWriter) -> None:")
        for item in s.fields:
            if isinstance(item, ReservedDef):
                lines.append(f"        w.bits(0, {item.bits})  # reserved")
            else:
                lines.append("        " + FIELD_TYPES[item.ftype].enc.format(a=snake(item.name)))
        lines.append("")
        lines.append("    @classmethod")
        lines.append("    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:")
        lines.append("        kw: dict[str, Any] = {}")
        for item in s.fields:
            if isinstance(item, ReservedDef):
                lines.append(f"        r.bits({item.bits})  # reserved")
            else:
                dec = FIELD_TYPES[item.ftype].dec
                if item.enum and item.ftype in SCALAR_ENUM_TYPES:
                    dec = f"maybe_enum({dec}, {ctx.enum_ref(item.enum)})"
                lines.append(f'        kw["{snake(item.name)}"] = {dec}')
        lines.append("        return kw")
    lines.append("")
    lines.append("")
    return lines


def emit_slot_assignments(structs: list[StructDef], ctx: EmitCtx) -> list[str]:
    lines: list[str] = []
    for s in structs:
        slots = struct_slots(s, ctx)
        if not slots:
            continue
        cname = class_name(s.name)
        lines.append(f"{cname}._SLOTS = (")
        for slot in slots:
            types = ", ".join(slot.classes) + ("," if len(slot.classes) == 1 else "")
            lines.append(
                f'    ParamSlot("{slot.attr}", ({types}), {slot.min_count}, {slot.is_list}),'
            )
        lines.append(")")
    if lines:
        lines.append("")
    return lines


def emit_enums_module(model: Model) -> str:
    out = [HEADER.format(title="Generated LLRP enumerations (LLRP 1.0.1).", source="llrpdef.xml")]
    out.append("\nfrom enum import IntEnum\n\n\n")
    body: list[str] = []
    for e in model.core_enums:
        body.extend(emit_enum_class(e))
    return "".join(out) + "\n".join(body).rstrip() + "\n"


COMMON_IMPORTS = """
from dataclasses import dataclass, field
from typing import Any, ClassVar

from llrpkit.protocol.codec import (
    BitStr,
    ByteReader,
    ByteWriter,
    CustomMessage,
    CustomParameter,
    LLRPMessage,
    LLRPParameter,
    ParamSlot,
    maybe_enum,
    register_message,
    register_parameter,
)
"""


def emit_params_module(model: Model) -> str:
    ctx = EmitCtx(model, "params")
    out = [
        HEADER.format(title="Generated LLRP parameter classes (LLRP 1.0.1).", source="llrpdef.xml")
    ]
    out.append(COMMON_IMPORTS)
    out.append("from llrpkit.protocol import enums\n\n\n")
    body: list[str] = []
    for s in model.core_params:
        body.extend(emit_struct(s, ctx))
    body.append("# --- containment slots (assigned after all classes exist) ---")
    body.append("")
    body.extend(emit_slot_assignments(model.core_params, ctx))
    return "".join(out) + "\n".join(body).rstrip() + "\n"


def emit_messages_module(model: Model) -> str:
    ctx = EmitCtx(model, "messages")
    out = [
        HEADER.format(title="Generated LLRP message classes (LLRP 1.0.1).", source="llrpdef.xml")
    ]
    out.append(COMMON_IMPORTS)
    out.append("from llrpkit.protocol import enums, params\n\n\n")
    body: list[str] = []
    for s in model.core_messages:
        body.extend(emit_struct(s, ctx))
    body.append("# --- containment slots (assigned after all classes exist) ---")
    body.append("")
    body.extend(emit_slot_assignments(model.core_messages, ctx))
    return "".join(out) + "\n".join(body).rstrip() + "\n"


def emit_impinj_module(model: Model) -> str:
    ctx = EmitCtx(model, "impinj")
    out = [
        HEADER.format(
            title=(
                f"Generated Impinj Octane LLRP extension classes (vendor PEN {model.vendor_id})."
            ),
            source="impinj.xml",
        )
    ]
    out.append(COMMON_IMPORTS)
    out.append("from enum import IntEnum\n")
    out.append("from llrpkit.protocol import enums, params\n\n\n")
    body: list[str] = []
    for e in model.vendor_enums:
        body.extend(emit_enum_class(e))
    for s in model.vendor_messages:
        body.extend(emit_struct(s, ctx, model.vendor_id))
    for s in model.vendor_params:
        body.extend(emit_struct(s, ctx, model.vendor_id))
    body.append("# --- containment slots (assigned after all classes exist) ---")
    body.append("")
    body.extend(emit_slot_assignments(model.vendor_messages + model.vendor_params, ctx))
    return "".join(out) + "\n".join(body).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed modules match the definitions; write nothing",
    )
    args = parser.parse_args(argv)

    model = Model()
    parse_core(CORE_XML, model)
    parse_vendor(IMPINJ_XML, model)

    outputs = {
        "enums.py": emit_enums_module(model),
        "params.py": emit_params_module(model),
        "messages.py": emit_messages_module(model),
        "impinj.py": emit_impinj_module(model),
    }

    if args.check:
        stale = []
        for fname, text in outputs.items():
            path = OUT_DIR / fname
            if not path.exists() or path.read_text() != text:
                stale.append(fname)
        if stale:
            print(f"STALE generated modules: {', '.join(stale)} — run codegen/generate.py")
            return 1
        print("Generated modules are up to date.")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for fname, text in outputs.items():
        (OUT_DIR / fname).write_text(text)
    print(
        f"Generated {len(model.core_enums)} enums, {len(model.core_params)} parameters, "
        f"{len(model.core_messages)} messages, "
        f"{len(model.vendor_enums)} + {len(model.vendor_messages)} + {len(model.vendor_params)} "
        f"Impinj definitions."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
