"""Generated LLRP enumerations (LLRP 1.0.1).

Generated by ``codegen/generate.py`` from ``codegen/llrpdef.xml`` — do not edit
by hand. Edit the definitions or the generator and regenerate.
"""

# ruff: noqa: E501, F401, I001, N801, N815, RUF100
from __future__ import annotations

from enum import IntEnum


class AirProtocols(IntEnum):
    """LLRP enumeration ``AirProtocols``."""

    Unspecified = 0
    EPCGlobalClass1Gen2 = 1


class GetReaderCapabilitiesRequestedData(IntEnum):
    """LLRP enumeration ``GetReaderCapabilitiesRequestedData``."""

    All = 0
    General_Device_Capabilities = 1
    LLRP_Capabilities = 2
    Regulatory_Capabilities = 3
    LLRP_Air_Protocol_Capabilities = 4


class CommunicationsStandard(IntEnum):
    """LLRP enumeration ``CommunicationsStandard``."""

    Unspecified = 0
    US_FCC_Part_15 = 1
    ETSI_302_208 = 2
    ETSI_300_220 = 3
    Australia_LIPD_1W = 4
    Australia_LIPD_4W = 5
    Japan_ARIB_STD_T89 = 6
    Hong_Kong_OFTA_1049 = 7
    Taiwan_DGT_LP0002 = 8
    Korea_MIC_Article_5_2 = 9


class ROSpecState(IntEnum):
    """LLRP enumeration ``ROSpecState``."""

    Disabled = 0
    Inactive = 1
    Active = 2


class ROSpecStartTriggerType(IntEnum):
    """LLRP enumeration ``ROSpecStartTriggerType``."""

    Null = 0
    Immediate = 1
    Periodic = 2
    GPI = 3


class ROSpecStopTriggerType(IntEnum):
    """LLRP enumeration ``ROSpecStopTriggerType``."""

    Null = 0
    Duration = 1
    GPI_With_Timeout = 2


class AISpecStopTriggerType(IntEnum):
    """LLRP enumeration ``AISpecStopTriggerType``."""

    Null = 0
    Duration = 1
    GPI_With_Timeout = 2
    Tag_Observation = 3


class TagObservationTriggerType(IntEnum):
    """LLRP enumeration ``TagObservationTriggerType``."""

    Upon_Seeing_N_Tags_Or_Timeout = 0
    Upon_Seeing_No_More_New_Tags_For_Tms_Or_Timeout = 1
    N_Attempts_To_See_All_Tags_In_FOV_Or_Timeout = 2


class RFSurveySpecStopTriggerType(IntEnum):
    """LLRP enumeration ``RFSurveySpecStopTriggerType``."""

    Null = 0
    Duration = 1
    N_Iterations_Through_Frequency_Range = 2


class AccessSpecState(IntEnum):
    """LLRP enumeration ``AccessSpecState``."""

    Disabled = 0
    Active = 1


class AccessSpecStopTriggerType(IntEnum):
    """LLRP enumeration ``AccessSpecStopTriggerType``."""

    Null = 0
    Operation_Count = 1


class GetReaderConfigRequestedData(IntEnum):
    """LLRP enumeration ``GetReaderConfigRequestedData``."""

    All = 0
    Identification = 1
    AntennaProperties = 2
    AntennaConfiguration = 3
    ROReportSpec = 4
    ReaderEventNotificationSpec = 5
    AccessReportSpec = 6
    LLRPConfigurationStateValue = 7
    KeepaliveSpec = 8
    GPIPortCurrentState = 9
    GPOWriteData = 10
    EventsAndReports = 11


class IdentificationType(IntEnum):
    """LLRP enumeration ``IdentificationType``."""

    MAC_Address = 0
    EPC = 1


class KeepaliveTriggerType(IntEnum):
    """LLRP enumeration ``KeepaliveTriggerType``."""

    Null = 0
    Periodic = 1


class GPIPortState(IntEnum):
    """LLRP enumeration ``GPIPortState``."""

    Low = 0
    High = 1
    Unknown = 2


class ROReportTriggerType(IntEnum):
    """LLRP enumeration ``ROReportTriggerType``."""

    None_ = 0
    Upon_N_Tags_Or_End_Of_AISpec = 1
    Upon_N_Tags_Or_End_Of_ROSpec = 2


class AccessReportTriggerType(IntEnum):
    """LLRP enumeration ``AccessReportTriggerType``."""

    Whenever_ROReport_Is_Generated = 0
    End_Of_AccessSpec = 1


class NotificationEventType(IntEnum):
    """LLRP enumeration ``NotificationEventType``."""

    Upon_Hopping_To_Next_Channel = 0
    GPI_Event = 1
    ROSpec_Event = 2
    Report_Buffer_Fill_Warning = 3
    Reader_Exception_Event = 4
    RFSurvey_Event = 5
    AISpec_Event = 6
    AISpec_Event_With_Details = 7
    Antenna_Event = 8


class ROSpecEventType(IntEnum):
    """LLRP enumeration ``ROSpecEventType``."""

    Start_Of_ROSpec = 0
    End_Of_ROSpec = 1
    Preemption_Of_ROSpec = 2


class RFSurveyEventType(IntEnum):
    """LLRP enumeration ``RFSurveyEventType``."""

    Start_Of_RFSurvey = 0
    End_Of_RFSurvey = 1


class AISpecEventType(IntEnum):
    """LLRP enumeration ``AISpecEventType``."""

    End_Of_AISpec = 0


class AntennaEventType(IntEnum):
    """LLRP enumeration ``AntennaEventType``."""

    Antenna_Disconnected = 0
    Antenna_Connected = 1


class ConnectionAttemptStatusType(IntEnum):
    """LLRP enumeration ``ConnectionAttemptStatusType``."""

    Success = 0
    Failed_A_Reader_Initiated_Connection_Already_Exists = 1
    Failed_A_Client_Initiated_Connection_Already_Exists = 2
    Failed_Reason_Other_Than_A_Connection_Already_Exists = 3
    Another_Connection_Attempted = 4


class StatusCode(IntEnum):
    """LLRP enumeration ``StatusCode``."""

    M_Success = 0
    M_ParameterError = 100
    M_FieldError = 101
    M_UnexpectedParameter = 102
    M_MissingParameter = 103
    M_DuplicateParameter = 104
    M_OverflowParameter = 105
    M_OverflowField = 106
    M_UnknownParameter = 107
    M_UnknownField = 108
    M_UnsupportedMessage = 109
    M_UnsupportedVersion = 110
    M_UnsupportedParameter = 111
    P_ParameterError = 200
    P_FieldError = 201
    P_UnexpectedParameter = 202
    P_MissingParameter = 203
    P_DuplicateParameter = 204
    P_OverflowParameter = 205
    P_OverflowField = 206
    P_UnknownParameter = 207
    P_UnknownField = 208
    P_UnsupportedParameter = 209
    A_Invalid = 300
    A_OutOfRange = 301
    R_DeviceError = 401


class C1G2DRValue(IntEnum):
    """LLRP enumeration ``C1G2DRValue``."""

    DRV_8 = 0
    DRV_64_3 = 1


class C1G2MValue(IntEnum):
    """LLRP enumeration ``C1G2MValue``."""

    MV_FM0 = 0
    MV_2 = 1
    MV_4 = 2
    MV_8 = 3


class C1G2ForwardLinkModulation(IntEnum):
    """LLRP enumeration ``C1G2ForwardLinkModulation``."""

    PR_ASK = 0
    SSB_ASK = 1
    DSB_ASK = 2


class C1G2SpectralMaskIndicator(IntEnum):
    """LLRP enumeration ``C1G2SpectralMaskIndicator``."""

    Unknown = 0
    SI = 1
    MI = 2
    DI = 3


class C1G2TruncateAction(IntEnum):
    """LLRP enumeration ``C1G2TruncateAction``."""

    Unspecified = 0
    Do_Not_Truncate = 1
    Truncate = 2


class C1G2StateAwareTarget(IntEnum):
    """LLRP enumeration ``C1G2StateAwareTarget``."""

    SL = 0
    Inventoried_State_For_Session_S0 = 1
    Inventoried_State_For_Session_S1 = 2
    Inventoried_State_For_Session_S2 = 3
    Inventoried_State_For_Session_S3 = 4


class C1G2StateAwareAction(IntEnum):
    """LLRP enumeration ``C1G2StateAwareAction``."""

    AssertSLOrA_DeassertSLOrB = 0
    AssertSLOrA_Noop = 1
    Noop_DeassertSLOrB = 2
    NegateSLOrABBA_Noop = 3
    DeassertSLOrB_AssertSLOrA = 4
    DeassertSLOrB_Noop = 5
    Noop_AssertSLOrA = 6
    Noop_NegateSLOrABBA = 7


class C1G2StateUnawareAction(IntEnum):
    """LLRP enumeration ``C1G2StateUnawareAction``."""

    Select_Unselect = 0
    Select_DoNothing = 1
    DoNothing_Unselect = 2
    Unselect_DoNothing = 3
    Unselect_Select = 4
    DoNothing_Select = 5


class C1G2TagInventoryStateAwareI(IntEnum):
    """LLRP enumeration ``C1G2TagInventoryStateAwareI``."""

    State_A = 0
    State_B = 1


class C1G2TagInventoryStateAwareS(IntEnum):
    """LLRP enumeration ``C1G2TagInventoryStateAwareS``."""

    SL = 0
    Not_SL = 1


class C1G2LockPrivilege(IntEnum):
    """LLRP enumeration ``C1G2LockPrivilege``."""

    Read_Write = 0
    Perma_Lock = 1
    Perma_Unlock = 2
    Unlock = 3


class C1G2LockDataField(IntEnum):
    """LLRP enumeration ``C1G2LockDataField``."""

    Kill_Password = 0
    Access_Password = 1
    EPC_Memory = 2
    TID_Memory = 3
    User_Memory = 4


class C1G2ReadResultType(IntEnum):
    """LLRP enumeration ``C1G2ReadResultType``."""

    Success = 0
    Nonspecific_Tag_Error = 1
    No_Response_From_Tag = 2
    Nonspecific_Reader_Error = 3


class C1G2WriteResultType(IntEnum):
    """LLRP enumeration ``C1G2WriteResultType``."""

    Success = 0
    Tag_Memory_Overrun_Error = 1
    Tag_Memory_Locked_Error = 2
    Insufficient_Power = 3
    Nonspecific_Tag_Error = 4
    No_Response_From_Tag = 5
    Nonspecific_Reader_Error = 6


class C1G2KillResultType(IntEnum):
    """LLRP enumeration ``C1G2KillResultType``."""

    Success = 0
    Zero_Kill_Password_Error = 1
    Insufficient_Power = 2
    Nonspecific_Tag_Error = 3
    No_Response_From_Tag = 4
    Nonspecific_Reader_Error = 5


class C1G2LockResultType(IntEnum):
    """LLRP enumeration ``C1G2LockResultType``."""

    Success = 0
    Insufficient_Power = 1
    Nonspecific_Tag_Error = 2
    No_Response_From_Tag = 3
    Nonspecific_Reader_Error = 4


class C1G2BlockEraseResultType(IntEnum):
    """LLRP enumeration ``C1G2BlockEraseResultType``."""

    Success = 0
    Tag_Memory_Overrun_Error = 1
    Tag_Memory_Locked_Error = 2
    Insufficient_Power = 3
    Nonspecific_Tag_Error = 4
    No_Response_From_Tag = 5
    Nonspecific_Reader_Error = 6


class C1G2BlockWriteResultType(IntEnum):
    """LLRP enumeration ``C1G2BlockWriteResultType``."""

    Success = 0
    Tag_Memory_Overrun_Error = 1
    Tag_Memory_Locked_Error = 2
    Insufficient_Power = 3
    Nonspecific_Tag_Error = 4
    No_Response_From_Tag = 5
    Nonspecific_Reader_Error = 6
