"""Generated Impinj Octane LLRP extension classes (vendor PEN 25882).

Generated by ``codegen/generate.py`` from ``codegen/impinj.xml`` — do not edit
by hand. Edit the definitions or the generator and regenerate.
"""

# ruff: noqa: E501, F401, I001, N801, N815, RUF100
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from llrpkit.protocol.codec import (
    BitStr,
    ByteReader,
    ByteWriter,
    CustomMessage,
    CustomParameter,
    LLRPMessage,
    LLRPParameter,
    ParamSlot,
    maybe_enum,
    register_message,
    register_parameter,
)
from enum import IntEnum
from llrpkit.protocol import enums, params


class ImpinjRequestedDataType(IntEnum):
    """LLRP enumeration ``ImpinjRequestedDataType``."""

    All_Capabilities = 1000
    Impinj_Detailed_Version = 1001
    Impinj_Frequency_Capabilities = 1002
    Impinj_Array_Capabilities = 1003
    All_Configuration = 2000
    Impinj_Sub_Regulatory_Region = 2001
    Impinj_Forklift_Configuration = 2002
    Impinj_GPI_Debounce_Configuration = 2003
    Impinj_Reader_Temperature = 2004
    Impinj_Link_Monitor_Configuration = 2005
    Impinj_Report_Buffer_Configuration = 2006
    Impinj_Access_Spec_Configuration = 2007
    Impinj_GPS_NMEA_Sentences = 2008
    Impinj_Advanced_GPO_Configuration = 2009
    Impinj_Tilt_Configuration = 2010
    Impinj_Beacon_Configuration = 2011
    Impinj_Antenna_Configuration = 2012
    Impinj_Location_Configuration = 2013
    Impinj_Transition_Configuration = 2014


class ImpinjRegulatoryRegion(IntEnum):
    """LLRP enumeration ``ImpinjRegulatoryRegion``."""

    FCC_Part_15_247 = 0
    ETSI_EN_300_220 = 1
    ETSI_EN_302_208_With_LBT = 2
    Hong_Kong_920_925_MHz = 3
    Taiwan_922_928_MHz = 4
    Japan_952_954_MHz = 5
    Japan_952_954_MHz_Low_Power = 6
    ETSI_EN_302_208_v1_2_1 = 7
    Korea_917_921_MHz = 8
    Malaysia_919_923_MHz = 9
    China_920_925_MHz = 10
    Japan_952_956_MHz_Without_LBT = 11
    South_Africa_915_919_MHz = 12
    Brazil_902_907_and_915_928_MHz = 13
    Thailand_920_925_MHz = 14
    Singapore_920_925_MHz = 15
    Australia_920_926_MHz = 16
    India_865_867_MHz = 17
    Uruguay_916_928_MHz = 18
    Vietnam_920_925_MHz = 19
    Israel_915_917_MHz = 20
    Philippines_918_920_MHz = 21
    Canada_Post = 22
    Indonesia_923_925_MHz = 23
    New_Zealand_921p5_928_MHz = 24
    Japan_916_921_MHz_Without_LBT = 25
    Latin_America_902_928_MHz = 26


class ImpinjInventorySearchType(IntEnum):
    """LLRP enumeration ``ImpinjInventorySearchType``."""

    Reader_Selected = 0
    Single_Target = 1
    Dual_Target = 2
    Single_Target_With_Suppression = 3


class ImpinjFixedFrequencyMode(IntEnum):
    """LLRP enumeration ``ImpinjFixedFrequencyMode``."""

    Disabled = 0
    Auto_Select = 1
    Channel_List = 2


class ImpinjReducedPowerMode(IntEnum):
    """LLRP enumeration ``ImpinjReducedPowerMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjLowDutyCycleMode(IntEnum):
    """LLRP enumeration ``ImpinjLowDutyCycleMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjLinkMonitorMode(IntEnum):
    """LLRP enumeration ``ImpinjLinkMonitorMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjReportBufferMode(IntEnum):
    """LLRP enumeration ``ImpinjReportBufferMode``."""

    Normal = 0
    Low_Latency = 1


class ImpinjSerializedTIDMode(IntEnum):
    """LLRP enumeration ``ImpinjSerializedTIDMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjRFPhaseAngleMode(IntEnum):
    """LLRP enumeration ``ImpinjRFPhaseAngleMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjPeakRSSIMode(IntEnum):
    """LLRP enumeration ``ImpinjPeakRSSIMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjGPSCoordinatesMode(IntEnum):
    """LLRP enumeration ``ImpinjGPSCoordinatesMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjOptimizedReadMode(IntEnum):
    """LLRP enumeration ``ImpinjOptimizedReadMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjAccessSpecOrderingMode(IntEnum):
    """LLRP enumeration ``ImpinjAccessSpecOrderingMode``."""

    FIFO = 0
    Ascending = 1


class ImpinjRFDopplerFrequencyMode(IntEnum):
    """LLRP enumeration ``ImpinjRFDopplerFrequencyMode``."""

    Disabled = 0
    Enabled = 1


class ImpinjAdvancedGPOMode(IntEnum):
    """LLRP enumeration ``ImpinjAdvancedGPOMode``."""

    Normal = 0
    Pulsed = 1
    Reader_Operational_Status = 2
    LLRP_Connection_Status = 3


class ImpinjHubConnectedType(IntEnum):
    """LLRP enumeration ``ImpinjHubConnectedType``."""

    Unknown = 0
    Disconnected = 1
    Connected = 2


class ImpinjHubFaultType(IntEnum):
    """LLRP enumeration ``ImpinjHubFaultType``."""

    No_Fault = 0
    RF_Power = 1
    RF_Power_On_Hub_1 = 2
    RF_Power_On_Hub_2 = 3
    RF_Power_On_Hub_3 = 4
    RF_Power_On_Hub_4 = 5
    No_Init = 6
    Serial_Overflow = 7
    Disconnected = 8


@register_message
@dataclass(kw_only=True)
class IMPINJ_ENABLE_EXTENSIONS(CustomMessage):
    """``IMPINJ_ENABLE_EXTENSIONS`` — vendor custom message, subtype 21."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 21

    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(0, 32)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        r.bits(32)  # reserved
        return kw


@register_message
@dataclass(kw_only=True)
class IMPINJ_ENABLE_EXTENSIONS_RESPONSE(CustomMessage):
    """``IMPINJ_ENABLE_EXTENSIONS_RESPONSE`` — vendor custom message, subtype 22."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 22

    llrp_status: params.LLRPStatus
    custom: list[CustomParameter] = field(default_factory=list)


@register_message
@dataclass(kw_only=True)
class IMPINJ_SAVE_SETTINGS(CustomMessage):
    """``IMPINJ_SAVE_SETTINGS`` — vendor custom message, subtype 23."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 23

    save_configuration: bool = False
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.save_configuration), 1)
        w.bits(0, 7)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["save_configuration"] = bool(r.bits(1))
        r.bits(7)  # reserved
        return kw


@register_message
@dataclass(kw_only=True)
class IMPINJ_SAVE_SETTINGS_RESPONSE(CustomMessage):
    """``IMPINJ_SAVE_SETTINGS_RESPONSE`` — vendor custom message, subtype 24."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 24

    llrp_status: params.LLRPStatus
    custom: list[CustomParameter] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class ImpinjRequestedData(CustomParameter):
    """``ImpinjRequestedData`` — vendor custom parameter, subtype 21."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 21

    requested_data: int = 0  # enum: ImpinjRequestedDataType
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.requested_data)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["requested_data"] = maybe_enum(r.u32(), ImpinjRequestedDataType)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjSubRegulatoryRegion(CustomParameter):
    """``ImpinjSubRegulatoryRegion`` — vendor custom parameter, subtype 22."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 22

    regulatory_region: int = 0  # enum: ImpinjRegulatoryRegion
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.regulatory_region)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["regulatory_region"] = maybe_enum(r.u16(), ImpinjRegulatoryRegion)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjInventorySearchMode(CustomParameter):
    """``ImpinjInventorySearchMode`` — vendor custom parameter, subtype 23."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 23

    inventory_search_mode: int = 0  # enum: ImpinjInventorySearchType
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.inventory_search_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["inventory_search_mode"] = maybe_enum(r.u16(), ImpinjInventorySearchType)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjFixedFrequencyList(CustomParameter):
    """``ImpinjFixedFrequencyList`` — vendor custom parameter, subtype 26."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 26

    fixed_frequency_mode: int = 0  # enum: ImpinjFixedFrequencyMode
    channel_list: list[int] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.fixed_frequency_mode)
        w.bits(0, 16)  # reserved
        w.u16v(self.channel_list)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["fixed_frequency_mode"] = maybe_enum(r.u16(), ImpinjFixedFrequencyMode)
        r.bits(16)  # reserved
        kw["channel_list"] = r.u16v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjReducedPowerFrequencyList(CustomParameter):
    """``ImpinjReducedPowerFrequencyList`` — vendor custom parameter, subtype 27."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 27

    reduced_power_mode: int = 0  # enum: ImpinjReducedPowerMode
    channel_list: list[int] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.reduced_power_mode)
        w.bits(0, 16)  # reserved
        w.u16v(self.channel_list)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["reduced_power_mode"] = maybe_enum(r.u16(), ImpinjReducedPowerMode)
        r.bits(16)  # reserved
        kw["channel_list"] = r.u16v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjLowDutyCycle(CustomParameter):
    """``ImpinjLowDutyCycle`` — vendor custom parameter, subtype 28."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 28

    low_duty_cycle_mode: int = 0  # enum: ImpinjLowDutyCycleMode
    empty_field_timeout: int = 0
    field_ping_interval: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.low_duty_cycle_mode)
        w.u16(self.empty_field_timeout)
        w.u16(self.field_ping_interval)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["low_duty_cycle_mode"] = maybe_enum(r.u16(), ImpinjLowDutyCycleMode)
        kw["empty_field_timeout"] = r.u16()
        kw["field_ping_interval"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjDetailedVersion(CustomParameter):
    """``ImpinjDetailedVersion`` — vendor custom parameter, subtype 29."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 29

    model_name: str = ""
    serial_number: str = ""
    software_version: str = ""
    firmware_version: str = ""
    fpga_version: str = ""
    pcba_version: str = ""
    impinj_hub_versions: ImpinjHubVersions | None = None
    impinj_array_version: ImpinjArrayVersion | None = None
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.utf8v(self.model_name)
        w.utf8v(self.serial_number)
        w.utf8v(self.software_version)
        w.utf8v(self.firmware_version)
        w.utf8v(self.fpga_version)
        w.utf8v(self.pcba_version)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["model_name"] = r.utf8v()
        kw["serial_number"] = r.utf8v()
        kw["software_version"] = r.utf8v()
        kw["firmware_version"] = r.utf8v()
        kw["fpga_version"] = r.utf8v()
        kw["pcba_version"] = r.utf8v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjFrequencyCapabilities(CustomParameter):
    """``ImpinjFrequencyCapabilities`` — vendor custom parameter, subtype 30."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 30

    frequency_list: list[int] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32v(self.frequency_list)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["frequency_list"] = r.u32v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjGPIDebounceConfiguration(CustomParameter):
    """``ImpinjGPIDebounceConfiguration`` — vendor custom parameter, subtype 36."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 36

    gpi_port_num: int = 0
    gp_idebounce_timer_m_sec: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.gpi_port_num)
        w.u32(self.gp_idebounce_timer_m_sec)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["gpi_port_num"] = r.u16()
        kw["gp_idebounce_timer_m_sec"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjReaderTemperature(CustomParameter):
    """``ImpinjReaderTemperature`` — vendor custom parameter, subtype 37."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 37

    temperature: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.s16(self.temperature)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["temperature"] = r.s16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjLinkMonitorConfiguration(CustomParameter):
    """``ImpinjLinkMonitorConfiguration`` — vendor custom parameter, subtype 38."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 38

    link_monitor_mode: int = 0  # enum: ImpinjLinkMonitorMode
    link_down_threshold: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.link_monitor_mode)
        w.u16(self.link_down_threshold)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["link_monitor_mode"] = maybe_enum(r.u16(), ImpinjLinkMonitorMode)
        kw["link_down_threshold"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjReportBufferConfiguration(CustomParameter):
    """``ImpinjReportBufferConfiguration`` — vendor custom parameter, subtype 39."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 39

    report_buffer_mode: int = 0  # enum: ImpinjReportBufferMode
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.report_buffer_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["report_buffer_mode"] = maybe_enum(r.u16(), ImpinjReportBufferMode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjAccessSpecConfiguration(CustomParameter):
    """``ImpinjAccessSpecConfiguration`` — vendor custom parameter, subtype 40."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 40

    impinj_block_write_word_count: ImpinjBlockWriteWordCount | None = None
    impinj_op_spec_retry_count: ImpinjOpSpecRetryCount | None = None
    impinj_access_spec_ordering: ImpinjAccessSpecOrdering | None = None
    custom: list[CustomParameter] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class ImpinjBlockWriteWordCount(CustomParameter):
    """``ImpinjBlockWriteWordCount`` — vendor custom parameter, subtype 41."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 41

    word_count: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.word_count)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["word_count"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjTagReportContentSelector(CustomParameter):
    """``ImpinjTagReportContentSelector`` — vendor custom parameter, subtype 50."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 50

    impinj_enable_serialized_t_id: ImpinjEnableSerializedTID | None = None
    impinj_enable_rf_phase_angle: ImpinjEnableRFPhaseAngle | None = None
    impinj_enable_peak_rssi: ImpinjEnablePeakRSSI | None = None
    impinj_enable_gps_coordinates: ImpinjEnableGPSCoordinates | None = None
    impinj_enable_optimized_read: ImpinjEnableOptimizedRead | None = None
    impinj_enable_rf_doppler_frequency: ImpinjEnableRFDopplerFrequency | None = None
    custom: list[CustomParameter] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class ImpinjEnableSerializedTID(CustomParameter):
    """``ImpinjEnableSerializedTID`` — vendor custom parameter, subtype 51."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 51

    serialized_t_id_mode: int = 0  # enum: ImpinjSerializedTIDMode
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.serialized_t_id_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["serialized_t_id_mode"] = maybe_enum(r.u16(), ImpinjSerializedTIDMode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjEnableRFPhaseAngle(CustomParameter):
    """``ImpinjEnableRFPhaseAngle`` — vendor custom parameter, subtype 52."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 52

    rf_phase_angle_mode: int = 0  # enum: ImpinjRFPhaseAngleMode
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.rf_phase_angle_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["rf_phase_angle_mode"] = maybe_enum(r.u16(), ImpinjRFPhaseAngleMode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjEnablePeakRSSI(CustomParameter):
    """``ImpinjEnablePeakRSSI`` — vendor custom parameter, subtype 53."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 53

    peak_rssi_mode: int = 0  # enum: ImpinjPeakRSSIMode
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.peak_rssi_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["peak_rssi_mode"] = maybe_enum(r.u16(), ImpinjPeakRSSIMode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjEnableGPSCoordinates(CustomParameter):
    """``ImpinjEnableGPSCoordinates`` — vendor custom parameter, subtype 54."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 54

    gps_coordinates_mode: int = 0  # enum: ImpinjGPSCoordinatesMode
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.gps_coordinates_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["gps_coordinates_mode"] = maybe_enum(r.u16(), ImpinjGPSCoordinatesMode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjSerializedTID(CustomParameter):
    """``ImpinjSerializedTID`` — vendor custom parameter, subtype 55."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 55

    t_id: list[int] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16v(self.t_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["t_id"] = r.u16v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjRFPhaseAngle(CustomParameter):
    """``ImpinjRFPhaseAngle`` — vendor custom parameter, subtype 56."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 56

    phase_angle: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.phase_angle)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["phase_angle"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjPeakRSSI(CustomParameter):
    """``ImpinjPeakRSSI`` — vendor custom parameter, subtype 57."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 57

    rssi: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.s16(self.rssi)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["rssi"] = r.s16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjGPSCoordinates(CustomParameter):
    """``ImpinjGPSCoordinates`` — vendor custom parameter, subtype 58."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 58

    latitude: int = 0
    longitude: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.s32(self.latitude)
        w.s32(self.longitude)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["latitude"] = r.s32()
        kw["longitude"] = r.s32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjOpSpecRetryCount(CustomParameter):
    """``ImpinjOpSpecRetryCount`` — vendor custom parameter, subtype 63."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 63

    retry_count: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.retry_count)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["retry_count"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjAdvancedGPOConfiguration(CustomParameter):
    """``ImpinjAdvancedGPOConfiguration`` — vendor custom parameter, subtype 64."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 64

    gpo_port_num: int = 0
    gpo_mode: int = 0  # enum: ImpinjAdvancedGPOMode
    gpo_pulse_duration_m_sec: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.gpo_port_num)
        w.u16(self.gpo_mode)
        w.u32(self.gpo_pulse_duration_m_sec)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["gpo_port_num"] = r.u16()
        kw["gpo_mode"] = maybe_enum(r.u16(), ImpinjAdvancedGPOMode)
        kw["gpo_pulse_duration_m_sec"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjEnableOptimizedRead(CustomParameter):
    """``ImpinjEnableOptimizedRead`` — vendor custom parameter, subtype 65."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 65

    optimized_read_mode: int = 0  # enum: ImpinjOptimizedReadMode
    c1_g2_reads: list[params.C1G2Read] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.optimized_read_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["optimized_read_mode"] = maybe_enum(r.u16(), ImpinjOptimizedReadMode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjAccessSpecOrdering(CustomParameter):
    """``ImpinjAccessSpecOrdering`` — vendor custom parameter, subtype 66."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 66

    ordering_mode: int = 0  # enum: ImpinjAccessSpecOrderingMode
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.ordering_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ordering_mode"] = maybe_enum(r.u16(), ImpinjAccessSpecOrderingMode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjEnableRFDopplerFrequency(CustomParameter):
    """``ImpinjEnableRFDopplerFrequency`` — vendor custom parameter, subtype 67."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 67

    rf_doppler_frequency_mode: int = 0  # enum: ImpinjRFDopplerFrequencyMode
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.rf_doppler_frequency_mode)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["rf_doppler_frequency_mode"] = maybe_enum(r.u16(), ImpinjRFDopplerFrequencyMode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjRFDopplerFrequency(CustomParameter):
    """``ImpinjRFDopplerFrequency`` — vendor custom parameter, subtype 68."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 68

    doppler_frequency: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.s16(self.doppler_frequency)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["doppler_frequency"] = r.s16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjArrayVersion(CustomParameter):
    """``ImpinjArrayVersion`` — vendor custom parameter, subtype 1520."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 1520

    serial_number: str = ""
    firmware_version: str = ""
    pcba_version: str = ""
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.utf8v(self.serial_number)
        w.utf8v(self.firmware_version)
        w.utf8v(self.pcba_version)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["serial_number"] = r.utf8v()
        kw["firmware_version"] = r.utf8v()
        kw["pcba_version"] = r.utf8v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ImpinjHubVersions(CustomParameter):
    """``ImpinjHubVersions`` — vendor custom parameter, subtype 1537."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 1537

    impinj_array_versions: list[ImpinjArrayVersion] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class ImpinjHubConfiguration(CustomParameter):
    """``ImpinjHubConfiguration`` — vendor custom parameter, subtype 1538."""

    VENDOR_ID: ClassVar[int] = 25882
    SUBTYPE: ClassVar[int] = 1538

    hub_id: int = 0
    connected: int = 0  # enum: ImpinjHubConnectedType
    fault: int = 0  # enum: ImpinjHubFaultType
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.hub_id)
        w.u16(self.connected)
        w.u16(self.fault)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["hub_id"] = r.u16()
        kw["connected"] = maybe_enum(r.u16(), ImpinjHubConnectedType)
        kw["fault"] = maybe_enum(r.u16(), ImpinjHubFaultType)
        return kw


# --- containment slots (assigned after all classes exist) ---

IMPINJ_ENABLE_EXTENSIONS._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
IMPINJ_ENABLE_EXTENSIONS_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
IMPINJ_SAVE_SETTINGS._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
IMPINJ_SAVE_SETTINGS_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjRequestedData._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjSubRegulatoryRegion._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjInventorySearchMode._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjFixedFrequencyList._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjReducedPowerFrequencyList._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjLowDutyCycle._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjDetailedVersion._SLOTS = (
    ParamSlot("impinj_hub_versions", (ImpinjHubVersions,), 0, False),
    ParamSlot("impinj_array_version", (ImpinjArrayVersion,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjFrequencyCapabilities._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjGPIDebounceConfiguration._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjReaderTemperature._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjLinkMonitorConfiguration._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjReportBufferConfiguration._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjAccessSpecConfiguration._SLOTS = (
    ParamSlot("impinj_block_write_word_count", (ImpinjBlockWriteWordCount,), 0, False),
    ParamSlot("impinj_op_spec_retry_count", (ImpinjOpSpecRetryCount,), 0, False),
    ParamSlot("impinj_access_spec_ordering", (ImpinjAccessSpecOrdering,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjBlockWriteWordCount._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjTagReportContentSelector._SLOTS = (
    ParamSlot("impinj_enable_serialized_t_id", (ImpinjEnableSerializedTID,), 0, False),
    ParamSlot("impinj_enable_rf_phase_angle", (ImpinjEnableRFPhaseAngle,), 0, False),
    ParamSlot("impinj_enable_peak_rssi", (ImpinjEnablePeakRSSI,), 0, False),
    ParamSlot("impinj_enable_gps_coordinates", (ImpinjEnableGPSCoordinates,), 0, False),
    ParamSlot("impinj_enable_optimized_read", (ImpinjEnableOptimizedRead,), 0, False),
    ParamSlot("impinj_enable_rf_doppler_frequency", (ImpinjEnableRFDopplerFrequency,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjEnableSerializedTID._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjEnableRFPhaseAngle._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjEnablePeakRSSI._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjEnableGPSCoordinates._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjSerializedTID._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjRFPhaseAngle._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjPeakRSSI._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjGPSCoordinates._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjOpSpecRetryCount._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjAdvancedGPOConfiguration._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjEnableOptimizedRead._SLOTS = (
    ParamSlot("c1_g2_reads", (params.C1G2Read,), 0, True),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjAccessSpecOrdering._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjEnableRFDopplerFrequency._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjRFDopplerFrequency._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjArrayVersion._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjHubVersions._SLOTS = (
    ParamSlot("impinj_array_versions", (ImpinjArrayVersion,), 1, True),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ImpinjHubConfiguration._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
