"""Generated LLRP message classes (LLRP 1.0.1).

Generated by ``codegen/generate.py`` from ``codegen/llrpdef.xml`` — do not edit
by hand. Edit the definitions or the generator and regenerate.
"""

# ruff: noqa: E501, F401, I001, N801, N815, RUF100
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from llrpkit.protocol.codec import (
    BitStr,
    ByteReader,
    ByteWriter,
    CustomMessage,
    CustomParameter,
    LLRPMessage,
    LLRPParameter,
    ParamSlot,
    maybe_enum,
    register_message,
    register_parameter,
)
from llrpkit.protocol import enums, params


@register_message
@dataclass(kw_only=True)
class GET_READER_CAPABILITIES(LLRPMessage):
    """``GET_READER_CAPABILITIES`` — LLRP message, type 1."""

    MESSAGE_TYPE: ClassVar[int] = 1

    requested_data: int = 0  # enum: GetReaderCapabilitiesRequestedData
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.requested_data)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["requested_data"] = maybe_enum(r.u8(), enums.GetReaderCapabilitiesRequestedData)
        return kw


@register_message
@dataclass(kw_only=True)
class GET_READER_CAPABILITIES_RESPONSE(LLRPMessage):
    """``GET_READER_CAPABILITIES_RESPONSE`` — LLRP message, type 11."""

    MESSAGE_TYPE: ClassVar[int] = 11

    llrp_status: params.LLRPStatus
    general_device_capabilities: params.GeneralDeviceCapabilities | None = None
    llrp_capabilities: params.LLRPCapabilities | None = None
    regulatory_capabilities: params.RegulatoryCapabilities | None = None
    air_protocol_llrp_capabilities: params.C1G2LLRPCapabilities | None = None
    custom: list[CustomParameter] = field(default_factory=list)


@register_message
@dataclass(kw_only=True)
class ADD_ROSPEC(LLRPMessage):
    """``ADD_ROSPEC`` — LLRP message, type 20."""

    MESSAGE_TYPE: ClassVar[int] = 20

    ro_spec: params.ROSpec


@register_message
@dataclass(kw_only=True)
class ADD_ROSPEC_RESPONSE(LLRPMessage):
    """``ADD_ROSPEC_RESPONSE`` — LLRP message, type 30."""

    MESSAGE_TYPE: ClassVar[int] = 30

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class DELETE_ROSPEC(LLRPMessage):
    """``DELETE_ROSPEC`` — LLRP message, type 21."""

    MESSAGE_TYPE: ClassVar[int] = 21

    ro_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.ro_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_id"] = r.u32()
        return kw


@register_message
@dataclass(kw_only=True)
class DELETE_ROSPEC_RESPONSE(LLRPMessage):
    """``DELETE_ROSPEC_RESPONSE`` — LLRP message, type 31."""

    MESSAGE_TYPE: ClassVar[int] = 31

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class START_ROSPEC(LLRPMessage):
    """``START_ROSPEC`` — LLRP message, type 22."""

    MESSAGE_TYPE: ClassVar[int] = 22

    ro_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.ro_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_id"] = r.u32()
        return kw


@register_message
@dataclass(kw_only=True)
class START_ROSPEC_RESPONSE(LLRPMessage):
    """``START_ROSPEC_RESPONSE`` — LLRP message, type 32."""

    MESSAGE_TYPE: ClassVar[int] = 32

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class STOP_ROSPEC(LLRPMessage):
    """``STOP_ROSPEC`` — LLRP message, type 23."""

    MESSAGE_TYPE: ClassVar[int] = 23

    ro_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.ro_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_id"] = r.u32()
        return kw


@register_message
@dataclass(kw_only=True)
class STOP_ROSPEC_RESPONSE(LLRPMessage):
    """``STOP_ROSPEC_RESPONSE`` — LLRP message, type 33."""

    MESSAGE_TYPE: ClassVar[int] = 33

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class ENABLE_ROSPEC(LLRPMessage):
    """``ENABLE_ROSPEC`` — LLRP message, type 24."""

    MESSAGE_TYPE: ClassVar[int] = 24

    ro_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.ro_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_id"] = r.u32()
        return kw


@register_message
@dataclass(kw_only=True)
class ENABLE_ROSPEC_RESPONSE(LLRPMessage):
    """``ENABLE_ROSPEC_RESPONSE`` — LLRP message, type 34."""

    MESSAGE_TYPE: ClassVar[int] = 34

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class DISABLE_ROSPEC(LLRPMessage):
    """``DISABLE_ROSPEC`` — LLRP message, type 25."""

    MESSAGE_TYPE: ClassVar[int] = 25

    ro_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.ro_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_id"] = r.u32()
        return kw


@register_message
@dataclass(kw_only=True)
class DISABLE_ROSPEC_RESPONSE(LLRPMessage):
    """``DISABLE_ROSPEC_RESPONSE`` — LLRP message, type 35."""

    MESSAGE_TYPE: ClassVar[int] = 35

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class GET_ROSPECS(LLRPMessage):
    """``GET_ROSPECS`` — LLRP message, type 26."""

    MESSAGE_TYPE: ClassVar[int] = 26


@register_message
@dataclass(kw_only=True)
class GET_ROSPECS_RESPONSE(LLRPMessage):
    """``GET_ROSPECS_RESPONSE`` — LLRP message, type 36."""

    MESSAGE_TYPE: ClassVar[int] = 36

    llrp_status: params.LLRPStatus
    ro_specs: list[params.ROSpec] = field(default_factory=list)


@register_message
@dataclass(kw_only=True)
class ADD_ACCESSSPEC(LLRPMessage):
    """``ADD_ACCESSSPEC`` — LLRP message, type 40."""

    MESSAGE_TYPE: ClassVar[int] = 40

    access_spec: params.AccessSpec


@register_message
@dataclass(kw_only=True)
class ADD_ACCESSSPEC_RESPONSE(LLRPMessage):
    """``ADD_ACCESSSPEC_RESPONSE`` — LLRP message, type 50."""

    MESSAGE_TYPE: ClassVar[int] = 50

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class DELETE_ACCESSSPEC(LLRPMessage):
    """``DELETE_ACCESSSPEC`` — LLRP message, type 41."""

    MESSAGE_TYPE: ClassVar[int] = 41

    access_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.access_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["access_spec_id"] = r.u32()
        return kw


@register_message
@dataclass(kw_only=True)
class DELETE_ACCESSSPEC_RESPONSE(LLRPMessage):
    """``DELETE_ACCESSSPEC_RESPONSE`` — LLRP message, type 51."""

    MESSAGE_TYPE: ClassVar[int] = 51

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class ENABLE_ACCESSSPEC(LLRPMessage):
    """``ENABLE_ACCESSSPEC`` — LLRP message, type 42."""

    MESSAGE_TYPE: ClassVar[int] = 42

    access_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.access_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["access_spec_id"] = r.u32()
        return kw


@register_message
@dataclass(kw_only=True)
class ENABLE_ACCESSSPEC_RESPONSE(LLRPMessage):
    """``ENABLE_ACCESSSPEC_RESPONSE`` — LLRP message, type 52."""

    MESSAGE_TYPE: ClassVar[int] = 52

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class DISABLE_ACCESSSPEC(LLRPMessage):
    """``DISABLE_ACCESSSPEC`` — LLRP message, type 43."""

    MESSAGE_TYPE: ClassVar[int] = 43

    access_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.access_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["access_spec_id"] = r.u32()
        return kw


@register_message
@dataclass(kw_only=True)
class DISABLE_ACCESSSPEC_RESPONSE(LLRPMessage):
    """``DISABLE_ACCESSSPEC_RESPONSE`` — LLRP message, type 53."""

    MESSAGE_TYPE: ClassVar[int] = 53

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class GET_ACCESSSPECS(LLRPMessage):
    """``GET_ACCESSSPECS`` — LLRP message, type 44."""

    MESSAGE_TYPE: ClassVar[int] = 44


@register_message
@dataclass(kw_only=True)
class GET_ACCESSSPECS_RESPONSE(LLRPMessage):
    """``GET_ACCESSSPECS_RESPONSE`` — LLRP message, type 54."""

    MESSAGE_TYPE: ClassVar[int] = 54

    llrp_status: params.LLRPStatus
    access_specs: list[params.AccessSpec] = field(default_factory=list)


@register_message
@dataclass(kw_only=True)
class GET_READER_CONFIG(LLRPMessage):
    """``GET_READER_CONFIG`` — LLRP message, type 2."""

    MESSAGE_TYPE: ClassVar[int] = 2

    antenna_id: int = 0
    requested_data: int = 0  # enum: GetReaderConfigRequestedData
    gpi_port_num: int = 0
    gpo_port_num: int = 0
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.antenna_id)
        w.u8(self.requested_data)
        w.u16(self.gpi_port_num)
        w.u16(self.gpo_port_num)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["antenna_id"] = r.u16()
        kw["requested_data"] = maybe_enum(r.u8(), enums.GetReaderConfigRequestedData)
        kw["gpi_port_num"] = r.u16()
        kw["gpo_port_num"] = r.u16()
        return kw


@register_message
@dataclass(kw_only=True)
class GET_READER_CONFIG_RESPONSE(LLRPMessage):
    """``GET_READER_CONFIG_RESPONSE`` — LLRP message, type 12."""

    MESSAGE_TYPE: ClassVar[int] = 12

    llrp_status: params.LLRPStatus
    identification: params.Identification | None = None
    antenna_properties: list[params.AntennaProperties] = field(default_factory=list)
    antenna_configurations: list[params.AntennaConfiguration] = field(default_factory=list)
    reader_event_notification_spec: params.ReaderEventNotificationSpec | None = None
    ro_report_spec: params.ROReportSpec | None = None
    access_report_spec: params.AccessReportSpec | None = None
    llrp_configuration_state_value: params.LLRPConfigurationStateValue | None = None
    keepalive_spec: params.KeepaliveSpec | None = None
    gpi_port_current_states: list[params.GPIPortCurrentState] = field(default_factory=list)
    gpo_write_datas: list[params.GPOWriteData] = field(default_factory=list)
    events_and_reports: params.EventsAndReports | None = None
    custom: list[CustomParameter] = field(default_factory=list)


@register_message
@dataclass(kw_only=True)
class SET_READER_CONFIG(LLRPMessage):
    """``SET_READER_CONFIG`` — LLRP message, type 3."""

    MESSAGE_TYPE: ClassVar[int] = 3

    reset_to_factory_default: bool = False
    reader_event_notification_spec: params.ReaderEventNotificationSpec | None = None
    antenna_properties: list[params.AntennaProperties] = field(default_factory=list)
    antenna_configurations: list[params.AntennaConfiguration] = field(default_factory=list)
    ro_report_spec: params.ROReportSpec | None = None
    access_report_spec: params.AccessReportSpec | None = None
    keepalive_spec: params.KeepaliveSpec | None = None
    gpo_write_datas: list[params.GPOWriteData] = field(default_factory=list)
    gpi_port_current_states: list[params.GPIPortCurrentState] = field(default_factory=list)
    events_and_reports: params.EventsAndReports | None = None
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.reset_to_factory_default), 1)
        w.bits(0, 7)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["reset_to_factory_default"] = bool(r.bits(1))
        r.bits(7)  # reserved
        return kw


@register_message
@dataclass(kw_only=True)
class SET_READER_CONFIG_RESPONSE(LLRPMessage):
    """``SET_READER_CONFIG_RESPONSE`` — LLRP message, type 13."""

    MESSAGE_TYPE: ClassVar[int] = 13

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class CLOSE_CONNECTION(LLRPMessage):
    """``CLOSE_CONNECTION`` — LLRP message, type 14."""

    MESSAGE_TYPE: ClassVar[int] = 14


@register_message
@dataclass(kw_only=True)
class CLOSE_CONNECTION_RESPONSE(LLRPMessage):
    """``CLOSE_CONNECTION_RESPONSE`` — LLRP message, type 4."""

    MESSAGE_TYPE: ClassVar[int] = 4

    llrp_status: params.LLRPStatus


@register_message
@dataclass(kw_only=True)
class GET_REPORT(LLRPMessage):
    """``GET_REPORT`` — LLRP message, type 60."""

    MESSAGE_TYPE: ClassVar[int] = 60


@register_message
@dataclass(kw_only=True)
class RO_ACCESS_REPORT(LLRPMessage):
    """``RO_ACCESS_REPORT`` — LLRP message, type 61."""

    MESSAGE_TYPE: ClassVar[int] = 61

    tag_report_datas: list[params.TagReportData] = field(default_factory=list)
    rf_survey_report_datas: list[params.RFSurveyReportData] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)


@register_message
@dataclass(kw_only=True)
class KEEPALIVE(LLRPMessage):
    """``KEEPALIVE`` — LLRP message, type 62."""

    MESSAGE_TYPE: ClassVar[int] = 62


@register_message
@dataclass(kw_only=True)
class KEEPALIVE_ACK(LLRPMessage):
    """``KEEPALIVE_ACK`` — LLRP message, type 72."""

    MESSAGE_TYPE: ClassVar[int] = 72


@register_message
@dataclass(kw_only=True)
class READER_EVENT_NOTIFICATION(LLRPMessage):
    """``READER_EVENT_NOTIFICATION`` — LLRP message, type 63."""

    MESSAGE_TYPE: ClassVar[int] = 63

    reader_event_notification_data: params.ReaderEventNotificationData


@register_message
@dataclass(kw_only=True)
class ENABLE_EVENTS_AND_REPORTS(LLRPMessage):
    """``ENABLE_EVENTS_AND_REPORTS`` — LLRP message, type 64."""

    MESSAGE_TYPE: ClassVar[int] = 64


@register_message
@dataclass(kw_only=True)
class ERROR_MESSAGE(LLRPMessage):
    """``ERROR_MESSAGE`` — LLRP message, type 100."""

    MESSAGE_TYPE: ClassVar[int] = 100

    llrp_status: params.LLRPStatus


# --- containment slots (assigned after all classes exist) ---

GET_READER_CAPABILITIES._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
GET_READER_CAPABILITIES_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
    ParamSlot("general_device_capabilities", (params.GeneralDeviceCapabilities,), 0, False),
    ParamSlot("llrp_capabilities", (params.LLRPCapabilities,), 0, False),
    ParamSlot("regulatory_capabilities", (params.RegulatoryCapabilities,), 0, False),
    ParamSlot("air_protocol_llrp_capabilities", (params.C1G2LLRPCapabilities,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ADD_ROSPEC._SLOTS = (
    ParamSlot("ro_spec", (params.ROSpec,), 1, False),
)
ADD_ROSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
DELETE_ROSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
START_ROSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
STOP_ROSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
ENABLE_ROSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
DISABLE_ROSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
GET_ROSPECS_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
    ParamSlot("ro_specs", (params.ROSpec,), 0, True),
)
ADD_ACCESSSPEC._SLOTS = (
    ParamSlot("access_spec", (params.AccessSpec,), 1, False),
)
ADD_ACCESSSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
DELETE_ACCESSSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
ENABLE_ACCESSSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
DISABLE_ACCESSSPEC_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
GET_ACCESSSPECS_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
    ParamSlot("access_specs", (params.AccessSpec,), 0, True),
)
GET_READER_CONFIG._SLOTS = (
    ParamSlot("custom", (CustomParameter,), 0, True),
)
GET_READER_CONFIG_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
    ParamSlot("identification", (params.Identification,), 0, False),
    ParamSlot("antenna_properties", (params.AntennaProperties,), 0, True),
    ParamSlot("antenna_configurations", (params.AntennaConfiguration,), 0, True),
    ParamSlot("reader_event_notification_spec", (params.ReaderEventNotificationSpec,), 0, False),
    ParamSlot("ro_report_spec", (params.ROReportSpec,), 0, False),
    ParamSlot("access_report_spec", (params.AccessReportSpec,), 0, False),
    ParamSlot("llrp_configuration_state_value", (params.LLRPConfigurationStateValue,), 0, False),
    ParamSlot("keepalive_spec", (params.KeepaliveSpec,), 0, False),
    ParamSlot("gpi_port_current_states", (params.GPIPortCurrentState,), 0, True),
    ParamSlot("gpo_write_datas", (params.GPOWriteData,), 0, True),
    ParamSlot("events_and_reports", (params.EventsAndReports,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
SET_READER_CONFIG._SLOTS = (
    ParamSlot("reader_event_notification_spec", (params.ReaderEventNotificationSpec,), 0, False),
    ParamSlot("antenna_properties", (params.AntennaProperties,), 0, True),
    ParamSlot("antenna_configurations", (params.AntennaConfiguration,), 0, True),
    ParamSlot("ro_report_spec", (params.ROReportSpec,), 0, False),
    ParamSlot("access_report_spec", (params.AccessReportSpec,), 0, False),
    ParamSlot("keepalive_spec", (params.KeepaliveSpec,), 0, False),
    ParamSlot("gpo_write_datas", (params.GPOWriteData,), 0, True),
    ParamSlot("gpi_port_current_states", (params.GPIPortCurrentState,), 0, True),
    ParamSlot("events_and_reports", (params.EventsAndReports,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
SET_READER_CONFIG_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
CLOSE_CONNECTION_RESPONSE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
RO_ACCESS_REPORT._SLOTS = (
    ParamSlot("tag_report_datas", (params.TagReportData,), 0, True),
    ParamSlot("rf_survey_report_datas", (params.RFSurveyReportData,), 0, True),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
READER_EVENT_NOTIFICATION._SLOTS = (
    ParamSlot("reader_event_notification_data", (params.ReaderEventNotificationData,), 1, False),
)
ERROR_MESSAGE._SLOTS = (
    ParamSlot("llrp_status", (params.LLRPStatus,), 1, False),
)
