"""Generated LLRP parameter classes (LLRP 1.0.1).

Generated by ``codegen/generate.py`` from ``codegen/llrpdef.xml`` — do not edit
by hand. Edit the definitions or the generator and regenerate.
"""

# ruff: noqa: E501, F401, I001, N801, N815, RUF100
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, ClassVar

from llrpkit.protocol.codec import (
    BitStr,
    ByteReader,
    ByteWriter,
    CustomMessage,
    CustomParameter,
    LLRPMessage,
    LLRPParameter,
    ParamSlot,
    maybe_enum,
    register_message,
    register_parameter,
)
from llrpkit.protocol import enums


@register_parameter
@dataclass(kw_only=True)
class UTCTimestamp(LLRPParameter):
    """``UTCTimestamp`` — LLRP TLV parameter, type 128."""

    PARAM_TYPE: ClassVar[int] = 128

    microseconds: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u64(self.microseconds)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["microseconds"] = r.u64()
        return kw


@register_parameter
@dataclass(kw_only=True)
class Uptime(LLRPParameter):
    """``Uptime`` — LLRP TLV parameter, type 129."""

    PARAM_TYPE: ClassVar[int] = 129

    microseconds: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u64(self.microseconds)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["microseconds"] = r.u64()
        return kw


@register_parameter
@dataclass(kw_only=True)
class GeneralDeviceCapabilities(LLRPParameter):
    """``GeneralDeviceCapabilities`` — LLRP TLV parameter, type 137."""

    PARAM_TYPE: ClassVar[int] = 137

    max_number_of_antenna_supported: int = 0
    can_set_antenna_properties: bool = False
    has_utc_clock_capability: bool = False
    device_manufacturer_name: int = 0
    model_name: int = 0
    reader_firmware_version: str = ""
    receive_sensitivity_table_entrys: list[ReceiveSensitivityTableEntry] = field(default_factory=list)
    per_antenna_receive_sensitivity_ranges: list[PerAntennaReceiveSensitivityRange] = field(default_factory=list)
    gpio_capabilities: GPIOCapabilities
    per_antenna_air_protocols: list[PerAntennaAirProtocol] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.max_number_of_antenna_supported)
        w.bits(int(self.can_set_antenna_properties), 1)
        w.bits(int(self.has_utc_clock_capability), 1)
        w.bits(0, 14)  # reserved
        w.u32(self.device_manufacturer_name)
        w.u32(self.model_name)
        w.utf8v(self.reader_firmware_version)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["max_number_of_antenna_supported"] = r.u16()
        kw["can_set_antenna_properties"] = bool(r.bits(1))
        kw["has_utc_clock_capability"] = bool(r.bits(1))
        r.bits(14)  # reserved
        kw["device_manufacturer_name"] = r.u32()
        kw["model_name"] = r.u32()
        kw["reader_firmware_version"] = r.utf8v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ReceiveSensitivityTableEntry(LLRPParameter):
    """``ReceiveSensitivityTableEntry`` — LLRP TLV parameter, type 139."""

    PARAM_TYPE: ClassVar[int] = 139

    index: int = 0
    receive_sensitivity_value: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.index)
        w.s16(self.receive_sensitivity_value)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["index"] = r.u16()
        kw["receive_sensitivity_value"] = r.s16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class PerAntennaReceiveSensitivityRange(LLRPParameter):
    """``PerAntennaReceiveSensitivityRange`` — LLRP TLV parameter, type 149."""

    PARAM_TYPE: ClassVar[int] = 149

    antenna_id: int = 0
    receive_sensitivity_index_min: int = 0
    receive_sensitivity_index_max: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.antenna_id)
        w.u16(self.receive_sensitivity_index_min)
        w.u16(self.receive_sensitivity_index_max)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["antenna_id"] = r.u16()
        kw["receive_sensitivity_index_min"] = r.u16()
        kw["receive_sensitivity_index_max"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class PerAntennaAirProtocol(LLRPParameter):
    """``PerAntennaAirProtocol`` — LLRP TLV parameter, type 140."""

    PARAM_TYPE: ClassVar[int] = 140

    antenna_id: int = 0
    protocol_id: bytes = b""  # enum: AirProtocols

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.antenna_id)
        w.u8v(self.protocol_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["antenna_id"] = r.u16()
        kw["protocol_id"] = r.u8v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class GPIOCapabilities(LLRPParameter):
    """``GPIOCapabilities`` — LLRP TLV parameter, type 141."""

    PARAM_TYPE: ClassVar[int] = 141

    num_gp_is: int = 0
    num_gp_os: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.num_gp_is)
        w.u16(self.num_gp_os)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["num_gp_is"] = r.u16()
        kw["num_gp_os"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class LLRPCapabilities(LLRPParameter):
    """``LLRPCapabilities`` — LLRP TLV parameter, type 142."""

    PARAM_TYPE: ClassVar[int] = 142

    can_do_rf_survey: bool = False
    can_report_buffer_fill_warning: bool = False
    supports_client_request_op_spec: bool = False
    can_do_tag_inventory_state_aware_singulation: bool = False
    supports_event_and_report_holding: bool = False
    max_num_priority_levels_supported: int = 0
    client_request_op_spec_timeout: int = 0
    max_num_ro_specs: int = 0
    max_num_specs_per_ro_spec: int = 0
    max_num_inventory_parameter_specs_per_ai_spec: int = 0
    max_num_access_specs: int = 0
    max_num_op_specs_per_access_spec: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.can_do_rf_survey), 1)
        w.bits(int(self.can_report_buffer_fill_warning), 1)
        w.bits(int(self.supports_client_request_op_spec), 1)
        w.bits(int(self.can_do_tag_inventory_state_aware_singulation), 1)
        w.bits(int(self.supports_event_and_report_holding), 1)
        w.bits(0, 3)  # reserved
        w.u8(self.max_num_priority_levels_supported)
        w.u16(self.client_request_op_spec_timeout)
        w.u32(self.max_num_ro_specs)
        w.u32(self.max_num_specs_per_ro_spec)
        w.u32(self.max_num_inventory_parameter_specs_per_ai_spec)
        w.u32(self.max_num_access_specs)
        w.u32(self.max_num_op_specs_per_access_spec)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["can_do_rf_survey"] = bool(r.bits(1))
        kw["can_report_buffer_fill_warning"] = bool(r.bits(1))
        kw["supports_client_request_op_spec"] = bool(r.bits(1))
        kw["can_do_tag_inventory_state_aware_singulation"] = bool(r.bits(1))
        kw["supports_event_and_report_holding"] = bool(r.bits(1))
        r.bits(3)  # reserved
        kw["max_num_priority_levels_supported"] = r.u8()
        kw["client_request_op_spec_timeout"] = r.u16()
        kw["max_num_ro_specs"] = r.u32()
        kw["max_num_specs_per_ro_spec"] = r.u32()
        kw["max_num_inventory_parameter_specs_per_ai_spec"] = r.u32()
        kw["max_num_access_specs"] = r.u32()
        kw["max_num_op_specs_per_access_spec"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class RegulatoryCapabilities(LLRPParameter):
    """``RegulatoryCapabilities`` — LLRP TLV parameter, type 143."""

    PARAM_TYPE: ClassVar[int] = 143

    country_code: int = 0
    communications_standard: int = 0  # enum: CommunicationsStandard
    uhf_band_capabilities: UHFBandCapabilities | None = None
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.country_code)
        w.u16(self.communications_standard)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["country_code"] = r.u16()
        kw["communications_standard"] = maybe_enum(r.u16(), enums.CommunicationsStandard)
        return kw


@register_parameter
@dataclass(kw_only=True)
class UHFBandCapabilities(LLRPParameter):
    """``UHFBandCapabilities`` — LLRP TLV parameter, type 144."""

    PARAM_TYPE: ClassVar[int] = 144

    transmit_power_level_table_entrys: list[TransmitPowerLevelTableEntry] = field(default_factory=list)
    frequency_information: FrequencyInformation
    air_protocol_uhfrf_mode_tables: list[C1G2UHFRFModeTable] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class TransmitPowerLevelTableEntry(LLRPParameter):
    """``TransmitPowerLevelTableEntry`` — LLRP TLV parameter, type 145."""

    PARAM_TYPE: ClassVar[int] = 145

    index: int = 0
    transmit_power_value: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.index)
        w.s16(self.transmit_power_value)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["index"] = r.u16()
        kw["transmit_power_value"] = r.s16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class FrequencyInformation(LLRPParameter):
    """``FrequencyInformation`` — LLRP TLV parameter, type 146."""

    PARAM_TYPE: ClassVar[int] = 146

    hopping: bool = False
    frequency_hop_tables: list[FrequencyHopTable] = field(default_factory=list)
    fixed_frequency_table: FixedFrequencyTable | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.hopping), 1)
        w.bits(0, 7)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["hopping"] = bool(r.bits(1))
        r.bits(7)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class FrequencyHopTable(LLRPParameter):
    """``FrequencyHopTable`` — LLRP TLV parameter, type 147."""

    PARAM_TYPE: ClassVar[int] = 147

    hop_table_id: int = 0
    frequency: list[int] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.hop_table_id)
        w.bits(0, 8)  # reserved
        w.u32v(self.frequency)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["hop_table_id"] = r.u8()
        r.bits(8)  # reserved
        kw["frequency"] = r.u32v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class FixedFrequencyTable(LLRPParameter):
    """``FixedFrequencyTable`` — LLRP TLV parameter, type 148."""

    PARAM_TYPE: ClassVar[int] = 148

    frequency: list[int] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32v(self.frequency)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["frequency"] = r.u32v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ROSpec(LLRPParameter):
    """``ROSpec`` — LLRP TLV parameter, type 177."""

    PARAM_TYPE: ClassVar[int] = 177

    ro_spec_id: int = 0
    priority: int = 0
    current_state: int = 0  # enum: ROSpecState
    ro_boundary_spec: ROBoundarySpec
    spec_parameters: list[AISpec | RFSurveySpec | CustomParameter] = field(default_factory=list)
    ro_report_spec: ROReportSpec | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.ro_spec_id)
        w.u8(self.priority)
        w.u8(self.current_state)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_id"] = r.u32()
        kw["priority"] = r.u8()
        kw["current_state"] = maybe_enum(r.u8(), enums.ROSpecState)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ROBoundarySpec(LLRPParameter):
    """``ROBoundarySpec`` — LLRP TLV parameter, type 178."""

    PARAM_TYPE: ClassVar[int] = 178

    ro_spec_start_trigger: ROSpecStartTrigger
    ro_spec_stop_trigger: ROSpecStopTrigger


@register_parameter
@dataclass(kw_only=True)
class ROSpecStartTrigger(LLRPParameter):
    """``ROSpecStartTrigger`` — LLRP TLV parameter, type 179."""

    PARAM_TYPE: ClassVar[int] = 179

    ro_spec_start_trigger_type: int = 0  # enum: ROSpecStartTriggerType
    periodic_trigger_value: PeriodicTriggerValue | None = None
    gpi_trigger_value: GPITriggerValue | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.ro_spec_start_trigger_type)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_start_trigger_type"] = maybe_enum(r.u8(), enums.ROSpecStartTriggerType)
        return kw


@register_parameter
@dataclass(kw_only=True)
class PeriodicTriggerValue(LLRPParameter):
    """``PeriodicTriggerValue`` — LLRP TLV parameter, type 180."""

    PARAM_TYPE: ClassVar[int] = 180

    offset: int = 0
    period: int = 0
    utc_timestamp: UTCTimestamp | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.offset)
        w.u32(self.period)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["offset"] = r.u32()
        kw["period"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class GPITriggerValue(LLRPParameter):
    """``GPITriggerValue`` — LLRP TLV parameter, type 181."""

    PARAM_TYPE: ClassVar[int] = 181

    gpi_port_num: int = 0
    gpi_event: bool = False
    timeout: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.gpi_port_num)
        w.bits(int(self.gpi_event), 1)
        w.bits(0, 7)  # reserved
        w.u32(self.timeout)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["gpi_port_num"] = r.u16()
        kw["gpi_event"] = bool(r.bits(1))
        r.bits(7)  # reserved
        kw["timeout"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ROSpecStopTrigger(LLRPParameter):
    """``ROSpecStopTrigger`` — LLRP TLV parameter, type 182."""

    PARAM_TYPE: ClassVar[int] = 182

    ro_spec_stop_trigger_type: int = 0  # enum: ROSpecStopTriggerType
    duration_trigger_value: int = 0
    gpi_trigger_value: GPITriggerValue | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.ro_spec_stop_trigger_type)
        w.u32(self.duration_trigger_value)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_stop_trigger_type"] = maybe_enum(r.u8(), enums.ROSpecStopTriggerType)
        kw["duration_trigger_value"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AISpec(LLRPParameter):
    """``AISpec`` — LLRP TLV parameter, type 183."""

    PARAM_TYPE: ClassVar[int] = 183

    antenna_ids: list[int] = field(default_factory=list)
    ai_spec_stop_trigger: AISpecStopTrigger
    inventory_parameter_specs: list[InventoryParameterSpec] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16v(self.antenna_ids)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["antenna_ids"] = r.u16v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AISpecStopTrigger(LLRPParameter):
    """``AISpecStopTrigger`` — LLRP TLV parameter, type 184."""

    PARAM_TYPE: ClassVar[int] = 184

    ai_spec_stop_trigger_type: int = 0  # enum: AISpecStopTriggerType
    duration_trigger: int = 0
    gpi_trigger_value: GPITriggerValue | None = None
    tag_observation_trigger: TagObservationTrigger | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.ai_spec_stop_trigger_type)
        w.u32(self.duration_trigger)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ai_spec_stop_trigger_type"] = maybe_enum(r.u8(), enums.AISpecStopTriggerType)
        kw["duration_trigger"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class TagObservationTrigger(LLRPParameter):
    """``TagObservationTrigger`` — LLRP TLV parameter, type 185."""

    PARAM_TYPE: ClassVar[int] = 185

    trigger_type: int = 0  # enum: TagObservationTriggerType
    number_of_tags: int = 0
    number_of_attempts: int = 0
    t: int = 0
    timeout: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.trigger_type)
        w.bits(0, 8)  # reserved
        w.u16(self.number_of_tags)
        w.u16(self.number_of_attempts)
        w.u16(self.t)
        w.u32(self.timeout)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["trigger_type"] = maybe_enum(r.u8(), enums.TagObservationTriggerType)
        r.bits(8)  # reserved
        kw["number_of_tags"] = r.u16()
        kw["number_of_attempts"] = r.u16()
        kw["t"] = r.u16()
        kw["timeout"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class InventoryParameterSpec(LLRPParameter):
    """``InventoryParameterSpec`` — LLRP TLV parameter, type 186."""

    PARAM_TYPE: ClassVar[int] = 186

    inventory_parameter_spec_id: int = 0
    protocol_id: int = 0  # enum: AirProtocols
    antenna_configurations: list[AntennaConfiguration] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.inventory_parameter_spec_id)
        w.u8(self.protocol_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["inventory_parameter_spec_id"] = r.u16()
        kw["protocol_id"] = maybe_enum(r.u8(), enums.AirProtocols)
        return kw


@register_parameter
@dataclass(kw_only=True)
class RFSurveySpec(LLRPParameter):
    """``RFSurveySpec`` — LLRP TLV parameter, type 187."""

    PARAM_TYPE: ClassVar[int] = 187

    antenna_id: int = 0
    start_frequency: int = 0
    end_frequency: int = 0
    rf_survey_spec_stop_trigger: RFSurveySpecStopTrigger
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.antenna_id)
        w.u32(self.start_frequency)
        w.u32(self.end_frequency)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["antenna_id"] = r.u16()
        kw["start_frequency"] = r.u32()
        kw["end_frequency"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class RFSurveySpecStopTrigger(LLRPParameter):
    """``RFSurveySpecStopTrigger`` — LLRP TLV parameter, type 188."""

    PARAM_TYPE: ClassVar[int] = 188

    stop_trigger_type: int = 0  # enum: RFSurveySpecStopTriggerType
    duration_period: int = 0
    n: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.stop_trigger_type)
        w.u32(self.duration_period)
        w.u32(self.n)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["stop_trigger_type"] = maybe_enum(r.u8(), enums.RFSurveySpecStopTriggerType)
        kw["duration_period"] = r.u32()
        kw["n"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AccessSpec(LLRPParameter):
    """``AccessSpec`` — LLRP TLV parameter, type 207."""

    PARAM_TYPE: ClassVar[int] = 207

    access_spec_id: int = 0
    antenna_id: int = 0
    protocol_id: int = 0  # enum: AirProtocols
    current_state: bool = False  # enum: AccessSpecState
    ro_spec_id: int = 0
    access_spec_stop_trigger: AccessSpecStopTrigger
    access_command: AccessCommand
    access_report_spec: AccessReportSpec | None = None
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.access_spec_id)
        w.u16(self.antenna_id)
        w.u8(self.protocol_id)
        w.bits(int(self.current_state), 1)
        w.bits(0, 7)  # reserved
        w.u32(self.ro_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["access_spec_id"] = r.u32()
        kw["antenna_id"] = r.u16()
        kw["protocol_id"] = maybe_enum(r.u8(), enums.AirProtocols)
        kw["current_state"] = bool(r.bits(1))
        r.bits(7)  # reserved
        kw["ro_spec_id"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AccessSpecStopTrigger(LLRPParameter):
    """``AccessSpecStopTrigger`` — LLRP TLV parameter, type 208."""

    PARAM_TYPE: ClassVar[int] = 208

    access_spec_stop_trigger: int = 0  # enum: AccessSpecStopTriggerType
    operation_count_value: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.access_spec_stop_trigger)
        w.u16(self.operation_count_value)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["access_spec_stop_trigger"] = maybe_enum(r.u8(), enums.AccessSpecStopTriggerType)
        kw["operation_count_value"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AccessCommand(LLRPParameter):
    """``AccessCommand`` — LLRP TLV parameter, type 209."""

    PARAM_TYPE: ClassVar[int] = 209

    air_protocol_tag_spec: C1G2TagSpec
    access_command_op_specs: list[C1G2Read | C1G2Write | C1G2Kill | C1G2Lock | C1G2BlockErase | C1G2BlockWrite] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class LLRPConfigurationStateValue(LLRPParameter):
    """``LLRPConfigurationStateValue`` — LLRP TLV parameter, type 217."""

    PARAM_TYPE: ClassVar[int] = 217

    llrp_configuration_state_value: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.llrp_configuration_state_value)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["llrp_configuration_state_value"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class Identification(LLRPParameter):
    """``Identification`` — LLRP TLV parameter, type 218."""

    PARAM_TYPE: ClassVar[int] = 218

    id_type: int = 0  # enum: IdentificationType
    reader_id: bytes = b""

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.id_type)
        w.u8v(self.reader_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["id_type"] = maybe_enum(r.u8(), enums.IdentificationType)
        kw["reader_id"] = r.u8v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class GPOWriteData(LLRPParameter):
    """``GPOWriteData`` — LLRP TLV parameter, type 219."""

    PARAM_TYPE: ClassVar[int] = 219

    gpo_port_number: int = 0
    gpo_data: bool = False

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.gpo_port_number)
        w.bits(int(self.gpo_data), 1)
        w.bits(0, 7)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["gpo_port_number"] = r.u16()
        kw["gpo_data"] = bool(r.bits(1))
        r.bits(7)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class KeepaliveSpec(LLRPParameter):
    """``KeepaliveSpec`` — LLRP TLV parameter, type 220."""

    PARAM_TYPE: ClassVar[int] = 220

    keepalive_trigger_type: int = 0  # enum: KeepaliveTriggerType
    periodic_trigger_value: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.keepalive_trigger_type)
        w.u32(self.periodic_trigger_value)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["keepalive_trigger_type"] = maybe_enum(r.u8(), enums.KeepaliveTriggerType)
        kw["periodic_trigger_value"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AntennaProperties(LLRPParameter):
    """``AntennaProperties`` — LLRP TLV parameter, type 221."""

    PARAM_TYPE: ClassVar[int] = 221

    antenna_connected: bool = False
    antenna_id: int = 0
    antenna_gain: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.antenna_connected), 1)
        w.bits(0, 7)  # reserved
        w.u16(self.antenna_id)
        w.s16(self.antenna_gain)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["antenna_connected"] = bool(r.bits(1))
        r.bits(7)  # reserved
        kw["antenna_id"] = r.u16()
        kw["antenna_gain"] = r.s16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AntennaConfiguration(LLRPParameter):
    """``AntennaConfiguration`` — LLRP TLV parameter, type 222."""

    PARAM_TYPE: ClassVar[int] = 222

    antenna_id: int = 0
    rf_receiver: RFReceiver | None = None
    rf_transmitter: RFTransmitter | None = None
    air_protocol_inventory_command_settings: list[C1G2InventoryCommand] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.antenna_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["antenna_id"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class RFReceiver(LLRPParameter):
    """``RFReceiver`` — LLRP TLV parameter, type 223."""

    PARAM_TYPE: ClassVar[int] = 223

    receiver_sensitivity: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.receiver_sensitivity)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["receiver_sensitivity"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class RFTransmitter(LLRPParameter):
    """``RFTransmitter`` — LLRP TLV parameter, type 224."""

    PARAM_TYPE: ClassVar[int] = 224

    hop_table_id: int = 0
    channel_index: int = 0
    transmit_power: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.hop_table_id)
        w.u16(self.channel_index)
        w.u16(self.transmit_power)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["hop_table_id"] = r.u16()
        kw["channel_index"] = r.u16()
        kw["transmit_power"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class GPIPortCurrentState(LLRPParameter):
    """``GPIPortCurrentState`` — LLRP TLV parameter, type 225."""

    PARAM_TYPE: ClassVar[int] = 225

    gpi_port_num: int = 0
    config: bool = False
    state: int = 0  # enum: GPIPortState

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.gpi_port_num)
        w.bits(int(self.config), 1)
        w.bits(0, 7)  # reserved
        w.u8(self.state)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["gpi_port_num"] = r.u16()
        kw["config"] = bool(r.bits(1))
        r.bits(7)  # reserved
        kw["state"] = maybe_enum(r.u8(), enums.GPIPortState)
        return kw


@register_parameter
@dataclass(kw_only=True)
class EventsAndReports(LLRPParameter):
    """``EventsAndReports`` — LLRP TLV parameter, type 226."""

    PARAM_TYPE: ClassVar[int] = 226

    hold_events_and_reports_upon_reconnect: bool = False

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.hold_events_and_reports_upon_reconnect), 1)
        w.bits(0, 7)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["hold_events_and_reports_upon_reconnect"] = bool(r.bits(1))
        r.bits(7)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class ROReportSpec(LLRPParameter):
    """``ROReportSpec`` — LLRP TLV parameter, type 237."""

    PARAM_TYPE: ClassVar[int] = 237

    ro_report_trigger: int = 0  # enum: ROReportTriggerType
    n: int = 0
    tag_report_content_selector: TagReportContentSelector
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.ro_report_trigger)
        w.u16(self.n)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_report_trigger"] = maybe_enum(r.u8(), enums.ROReportTriggerType)
        kw["n"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class TagReportContentSelector(LLRPParameter):
    """``TagReportContentSelector`` — LLRP TLV parameter, type 238."""

    PARAM_TYPE: ClassVar[int] = 238

    enable_ro_spec_id: bool = False
    enable_spec_index: bool = False
    enable_inventory_parameter_spec_id: bool = False
    enable_antenna_id: bool = False
    enable_channel_index: bool = False
    enable_peak_rssi: bool = False
    enable_first_seen_timestamp: bool = False
    enable_last_seen_timestamp: bool = False
    enable_tag_seen_count: bool = False
    enable_access_spec_id: bool = False
    air_protocol_epc_memory_selectors: list[C1G2EPCMemorySelector] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.enable_ro_spec_id), 1)
        w.bits(int(self.enable_spec_index), 1)
        w.bits(int(self.enable_inventory_parameter_spec_id), 1)
        w.bits(int(self.enable_antenna_id), 1)
        w.bits(int(self.enable_channel_index), 1)
        w.bits(int(self.enable_peak_rssi), 1)
        w.bits(int(self.enable_first_seen_timestamp), 1)
        w.bits(int(self.enable_last_seen_timestamp), 1)
        w.bits(int(self.enable_tag_seen_count), 1)
        w.bits(int(self.enable_access_spec_id), 1)
        w.bits(0, 6)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["enable_ro_spec_id"] = bool(r.bits(1))
        kw["enable_spec_index"] = bool(r.bits(1))
        kw["enable_inventory_parameter_spec_id"] = bool(r.bits(1))
        kw["enable_antenna_id"] = bool(r.bits(1))
        kw["enable_channel_index"] = bool(r.bits(1))
        kw["enable_peak_rssi"] = bool(r.bits(1))
        kw["enable_first_seen_timestamp"] = bool(r.bits(1))
        kw["enable_last_seen_timestamp"] = bool(r.bits(1))
        kw["enable_tag_seen_count"] = bool(r.bits(1))
        kw["enable_access_spec_id"] = bool(r.bits(1))
        r.bits(6)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class AccessReportSpec(LLRPParameter):
    """``AccessReportSpec`` — LLRP TLV parameter, type 239."""

    PARAM_TYPE: ClassVar[int] = 239

    access_report_trigger: int = 0  # enum: AccessReportTriggerType

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.access_report_trigger)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["access_report_trigger"] = maybe_enum(r.u8(), enums.AccessReportTriggerType)
        return kw


@register_parameter
@dataclass(kw_only=True)
class TagReportData(LLRPParameter):
    """``TagReportData`` — LLRP TLV parameter, type 240."""

    PARAM_TYPE: ClassVar[int] = 240

    epc_parameter: EPCData | EPC_96
    ro_spec_id: ROSpecID | None = None
    spec_index: SpecIndex | None = None
    inventory_parameter_spec_id: InventoryParameterSpecID | None = None
    antenna_id: AntennaID | None = None
    peak_rssi: PeakRSSI | None = None
    channel_index: ChannelIndex | None = None
    first_seen_timestamp_utc: FirstSeenTimestampUTC | None = None
    first_seen_timestamp_uptime: FirstSeenTimestampUptime | None = None
    last_seen_timestamp_utc: LastSeenTimestampUTC | None = None
    last_seen_timestamp_uptime: LastSeenTimestampUptime | None = None
    tag_seen_count: TagSeenCount | None = None
    air_protocol_tag_datas: list[C1G2_PC | C1G2_CRC] = field(default_factory=list)
    access_spec_id: AccessSpecID | None = None
    access_command_op_spec_results: list[C1G2ReadOpSpecResult | C1G2WriteOpSpecResult | C1G2KillOpSpecResult | C1G2LockOpSpecResult | C1G2BlockEraseOpSpecResult | C1G2BlockWriteOpSpecResult] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class EPCData(LLRPParameter):
    """``EPCData`` — LLRP TLV parameter, type 241."""

    PARAM_TYPE: ClassVar[int] = 241

    epc: BitStr = field(default_factory=BitStr)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u1v(self.epc)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["epc"] = r.u1v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class EPC_96(LLRPParameter):
    """``EPC_96`` — LLRP TV parameter, type 13."""

    PARAM_TYPE: ClassVar[int] = 13
    IS_TV: ClassVar[bool] = True

    epc: bytes = b"\x00" * 12

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u96(self.epc)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["epc"] = r.u96()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ROSpecID(LLRPParameter):
    """``ROSpecID`` — LLRP TV parameter, type 9."""

    PARAM_TYPE: ClassVar[int] = 9
    IS_TV: ClassVar[bool] = True

    ro_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.ro_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["ro_spec_id"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class SpecIndex(LLRPParameter):
    """``SpecIndex`` — LLRP TV parameter, type 14."""

    PARAM_TYPE: ClassVar[int] = 14
    IS_TV: ClassVar[bool] = True

    spec_index: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.spec_index)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["spec_index"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class InventoryParameterSpecID(LLRPParameter):
    """``InventoryParameterSpecID`` — LLRP TV parameter, type 10."""

    PARAM_TYPE: ClassVar[int] = 10
    IS_TV: ClassVar[bool] = True

    inventory_parameter_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.inventory_parameter_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["inventory_parameter_spec_id"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AntennaID(LLRPParameter):
    """``AntennaID`` — LLRP TV parameter, type 1."""

    PARAM_TYPE: ClassVar[int] = 1
    IS_TV: ClassVar[bool] = True

    antenna_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.antenna_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["antenna_id"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class PeakRSSI(LLRPParameter):
    """``PeakRSSI`` — LLRP TV parameter, type 6."""

    PARAM_TYPE: ClassVar[int] = 6
    IS_TV: ClassVar[bool] = True

    peak_rssi: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.s8(self.peak_rssi)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["peak_rssi"] = r.s8()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ChannelIndex(LLRPParameter):
    """``ChannelIndex`` — LLRP TV parameter, type 7."""

    PARAM_TYPE: ClassVar[int] = 7
    IS_TV: ClassVar[bool] = True

    channel_index: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.channel_index)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["channel_index"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class FirstSeenTimestampUTC(LLRPParameter):
    """``FirstSeenTimestampUTC`` — LLRP TV parameter, type 2."""

    PARAM_TYPE: ClassVar[int] = 2
    IS_TV: ClassVar[bool] = True

    microseconds: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u64(self.microseconds)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["microseconds"] = r.u64()
        return kw


@register_parameter
@dataclass(kw_only=True)
class FirstSeenTimestampUptime(LLRPParameter):
    """``FirstSeenTimestampUptime`` — LLRP TV parameter, type 3."""

    PARAM_TYPE: ClassVar[int] = 3
    IS_TV: ClassVar[bool] = True

    microseconds: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u64(self.microseconds)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["microseconds"] = r.u64()
        return kw


@register_parameter
@dataclass(kw_only=True)
class LastSeenTimestampUTC(LLRPParameter):
    """``LastSeenTimestampUTC`` — LLRP TV parameter, type 4."""

    PARAM_TYPE: ClassVar[int] = 4
    IS_TV: ClassVar[bool] = True

    microseconds: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u64(self.microseconds)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["microseconds"] = r.u64()
        return kw


@register_parameter
@dataclass(kw_only=True)
class LastSeenTimestampUptime(LLRPParameter):
    """``LastSeenTimestampUptime`` — LLRP TV parameter, type 5."""

    PARAM_TYPE: ClassVar[int] = 5
    IS_TV: ClassVar[bool] = True

    microseconds: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u64(self.microseconds)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["microseconds"] = r.u64()
        return kw


@register_parameter
@dataclass(kw_only=True)
class TagSeenCount(LLRPParameter):
    """``TagSeenCount`` — LLRP TV parameter, type 8."""

    PARAM_TYPE: ClassVar[int] = 8
    IS_TV: ClassVar[bool] = True

    tag_count: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.tag_count)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["tag_count"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AccessSpecID(LLRPParameter):
    """``AccessSpecID`` — LLRP TV parameter, type 16."""

    PARAM_TYPE: ClassVar[int] = 16
    IS_TV: ClassVar[bool] = True

    access_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.access_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["access_spec_id"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class RFSurveyReportData(LLRPParameter):
    """``RFSurveyReportData`` — LLRP TLV parameter, type 242."""

    PARAM_TYPE: ClassVar[int] = 242

    ro_spec_id: ROSpecID | None = None
    spec_index: SpecIndex | None = None
    frequency_rssi_level_entrys: list[FrequencyRSSILevelEntry] = field(default_factory=list)
    custom: list[CustomParameter] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class FrequencyRSSILevelEntry(LLRPParameter):
    """``FrequencyRSSILevelEntry`` — LLRP TLV parameter, type 243."""

    PARAM_TYPE: ClassVar[int] = 243

    frequency: int = 0
    bandwidth: int = 0
    average_rssi: int = 0
    peak_rssi: int = 0
    timestamp: UTCTimestamp | Uptime

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.frequency)
        w.u32(self.bandwidth)
        w.s8(self.average_rssi)
        w.s8(self.peak_rssi)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["frequency"] = r.u32()
        kw["bandwidth"] = r.u32()
        kw["average_rssi"] = r.s8()
        kw["peak_rssi"] = r.s8()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ReaderEventNotificationSpec(LLRPParameter):
    """``ReaderEventNotificationSpec`` — LLRP TLV parameter, type 244."""

    PARAM_TYPE: ClassVar[int] = 244

    event_notification_states: list[EventNotificationState] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class EventNotificationState(LLRPParameter):
    """``EventNotificationState`` — LLRP TLV parameter, type 245."""

    PARAM_TYPE: ClassVar[int] = 245

    event_type: int = 0  # enum: NotificationEventType
    notification_state: bool = False

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.event_type)
        w.bits(int(self.notification_state), 1)
        w.bits(0, 7)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["event_type"] = maybe_enum(r.u16(), enums.NotificationEventType)
        kw["notification_state"] = bool(r.bits(1))
        r.bits(7)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class ReaderEventNotificationData(LLRPParameter):
    """``ReaderEventNotificationData`` — LLRP TLV parameter, type 246."""

    PARAM_TYPE: ClassVar[int] = 246

    timestamp: UTCTimestamp | Uptime
    hopping_event: HoppingEvent | None = None
    gpi_event: GPIEvent | None = None
    ro_spec_event: ROSpecEvent | None = None
    report_buffer_level_warning_event: ReportBufferLevelWarningEvent | None = None
    report_buffer_overflow_error_event: ReportBufferOverflowErrorEvent | None = None
    reader_exception_event: ReaderExceptionEvent | None = None
    rf_survey_event: RFSurveyEvent | None = None
    ai_spec_event: AISpecEvent | None = None
    antenna_event: AntennaEvent | None = None
    connection_attempt_event: ConnectionAttemptEvent | None = None
    connection_close_event: ConnectionCloseEvent | None = None
    custom: list[CustomParameter] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class HoppingEvent(LLRPParameter):
    """``HoppingEvent`` — LLRP TLV parameter, type 247."""

    PARAM_TYPE: ClassVar[int] = 247

    hop_table_id: int = 0
    next_channel_index: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.hop_table_id)
        w.u16(self.next_channel_index)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["hop_table_id"] = r.u16()
        kw["next_channel_index"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class GPIEvent(LLRPParameter):
    """``GPIEvent`` — LLRP TLV parameter, type 248."""

    PARAM_TYPE: ClassVar[int] = 248

    gpi_port_number: int = 0
    gpi_event: bool = False

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.gpi_port_number)
        w.bits(int(self.gpi_event), 1)
        w.bits(0, 7)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["gpi_port_number"] = r.u16()
        kw["gpi_event"] = bool(r.bits(1))
        r.bits(7)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class ROSpecEvent(LLRPParameter):
    """``ROSpecEvent`` — LLRP TLV parameter, type 249."""

    PARAM_TYPE: ClassVar[int] = 249

    event_type: int = 0  # enum: ROSpecEventType
    ro_spec_id: int = 0
    preempting_ro_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.event_type)
        w.u32(self.ro_spec_id)
        w.u32(self.preempting_ro_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["event_type"] = maybe_enum(r.u8(), enums.ROSpecEventType)
        kw["ro_spec_id"] = r.u32()
        kw["preempting_ro_spec_id"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ReportBufferLevelWarningEvent(LLRPParameter):
    """``ReportBufferLevelWarningEvent`` — LLRP TLV parameter, type 250."""

    PARAM_TYPE: ClassVar[int] = 250

    report_buffer_percentage_full: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.report_buffer_percentage_full)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["report_buffer_percentage_full"] = r.u8()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ReportBufferOverflowErrorEvent(LLRPParameter):
    """``ReportBufferOverflowErrorEvent`` — LLRP TLV parameter, type 251."""

    PARAM_TYPE: ClassVar[int] = 251


@register_parameter
@dataclass(kw_only=True)
class ReaderExceptionEvent(LLRPParameter):
    """``ReaderExceptionEvent`` — LLRP TLV parameter, type 252."""

    PARAM_TYPE: ClassVar[int] = 252

    message: str = ""
    ro_spec_id: ROSpecID | None = None
    spec_index: SpecIndex | None = None
    inventory_parameter_spec_id: InventoryParameterSpecID | None = None
    antenna_id: AntennaID | None = None
    access_spec_id: AccessSpecID | None = None
    op_spec_id: OpSpecID | None = None
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.utf8v(self.message)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["message"] = r.utf8v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class OpSpecID(LLRPParameter):
    """``OpSpecID`` — LLRP TV parameter, type 17."""

    PARAM_TYPE: ClassVar[int] = 17
    IS_TV: ClassVar[bool] = True

    op_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.op_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["op_spec_id"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class RFSurveyEvent(LLRPParameter):
    """``RFSurveyEvent`` — LLRP TLV parameter, type 253."""

    PARAM_TYPE: ClassVar[int] = 253

    event_type: int = 0  # enum: RFSurveyEventType
    ro_spec_id: int = 0
    spec_index: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.event_type)
        w.u32(self.ro_spec_id)
        w.u16(self.spec_index)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["event_type"] = maybe_enum(r.u8(), enums.RFSurveyEventType)
        kw["ro_spec_id"] = r.u32()
        kw["spec_index"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AISpecEvent(LLRPParameter):
    """``AISpecEvent`` — LLRP TLV parameter, type 254."""

    PARAM_TYPE: ClassVar[int] = 254

    event_type: int = 0  # enum: AISpecEventType
    ro_spec_id: int = 0
    spec_index: int = 0
    air_protocol_singulation_details: C1G2SingulationDetails | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.event_type)
        w.u32(self.ro_spec_id)
        w.u16(self.spec_index)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["event_type"] = maybe_enum(r.u8(), enums.AISpecEventType)
        kw["ro_spec_id"] = r.u32()
        kw["spec_index"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class AntennaEvent(LLRPParameter):
    """``AntennaEvent`` — LLRP TLV parameter, type 255."""

    PARAM_TYPE: ClassVar[int] = 255

    event_type: int = 0  # enum: AntennaEventType
    antenna_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.event_type)
        w.u16(self.antenna_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["event_type"] = maybe_enum(r.u8(), enums.AntennaEventType)
        kw["antenna_id"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class ConnectionAttemptEvent(LLRPParameter):
    """``ConnectionAttemptEvent`` — LLRP TLV parameter, type 256."""

    PARAM_TYPE: ClassVar[int] = 256

    status: int = 0  # enum: ConnectionAttemptStatusType

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.status)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["status"] = maybe_enum(r.u16(), enums.ConnectionAttemptStatusType)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ConnectionCloseEvent(LLRPParameter):
    """``ConnectionCloseEvent`` — LLRP TLV parameter, type 257."""

    PARAM_TYPE: ClassVar[int] = 257


@register_parameter
@dataclass(kw_only=True)
class LLRPStatus(LLRPParameter):
    """``LLRPStatus`` — LLRP TLV parameter, type 287."""

    PARAM_TYPE: ClassVar[int] = 287

    status_code: int = 0  # enum: StatusCode
    error_description: str = ""
    field_error: FieldError | None = None
    parameter_error: ParameterError | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.status_code)
        w.utf8v(self.error_description)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["status_code"] = maybe_enum(r.u16(), enums.StatusCode)
        kw["error_description"] = r.utf8v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class FieldError(LLRPParameter):
    """``FieldError`` — LLRP TLV parameter, type 288."""

    PARAM_TYPE: ClassVar[int] = 288

    field_num: int = 0
    error_code: int = 0  # enum: StatusCode

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.field_num)
        w.u16(self.error_code)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["field_num"] = r.u16()
        kw["error_code"] = maybe_enum(r.u16(), enums.StatusCode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class ParameterError(LLRPParameter):
    """``ParameterError`` — LLRP TLV parameter, type 289."""

    PARAM_TYPE: ClassVar[int] = 289

    parameter_type: int = 0
    error_code: int = 0  # enum: StatusCode
    field_error: FieldError | None = None
    parameter_error: ParameterError | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.parameter_type)
        w.u16(self.error_code)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["parameter_type"] = r.u16()
        kw["error_code"] = maybe_enum(r.u16(), enums.StatusCode)
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2LLRPCapabilities(LLRPParameter):
    """``C1G2LLRPCapabilities`` — LLRP TLV parameter, type 327."""

    PARAM_TYPE: ClassVar[int] = 327

    can_support_block_erase: bool = False
    can_support_block_write: bool = False
    max_num_select_filters_per_query: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.can_support_block_erase), 1)
        w.bits(int(self.can_support_block_write), 1)
        w.bits(0, 6)  # reserved
        w.u16(self.max_num_select_filters_per_query)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["can_support_block_erase"] = bool(r.bits(1))
        kw["can_support_block_write"] = bool(r.bits(1))
        r.bits(6)  # reserved
        kw["max_num_select_filters_per_query"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2UHFRFModeTable(LLRPParameter):
    """``C1G2UHFRFModeTable`` — LLRP TLV parameter, type 328."""

    PARAM_TYPE: ClassVar[int] = 328

    c1_g2_uhfrf_mode_table_entrys: list[C1G2UHFRFModeTableEntry] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class C1G2UHFRFModeTableEntry(LLRPParameter):
    """``C1G2UHFRFModeTableEntry`` — LLRP TLV parameter, type 329."""

    PARAM_TYPE: ClassVar[int] = 329

    mode_identifier: int = 0
    dr_value: bool = False  # enum: C1G2DRValue
    epchagtc_conformance: bool = False
    m_value: int = 0  # enum: C1G2MValue
    forward_link_modulation: int = 0  # enum: C1G2ForwardLinkModulation
    spectral_mask_indicator: int = 0  # enum: C1G2SpectralMaskIndicator
    bdr_value: int = 0
    pie_value: int = 0
    min_tari_value: int = 0
    max_tari_value: int = 0
    step_tari_value: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u32(self.mode_identifier)
        w.bits(int(self.dr_value), 1)
        w.bits(int(self.epchagtc_conformance), 1)
        w.bits(0, 6)  # reserved
        w.u8(self.m_value)
        w.u8(self.forward_link_modulation)
        w.u8(self.spectral_mask_indicator)
        w.u32(self.bdr_value)
        w.u32(self.pie_value)
        w.u32(self.min_tari_value)
        w.u32(self.max_tari_value)
        w.u32(self.step_tari_value)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["mode_identifier"] = r.u32()
        kw["dr_value"] = bool(r.bits(1))
        kw["epchagtc_conformance"] = bool(r.bits(1))
        r.bits(6)  # reserved
        kw["m_value"] = maybe_enum(r.u8(), enums.C1G2MValue)
        kw["forward_link_modulation"] = maybe_enum(r.u8(), enums.C1G2ForwardLinkModulation)
        kw["spectral_mask_indicator"] = maybe_enum(r.u8(), enums.C1G2SpectralMaskIndicator)
        kw["bdr_value"] = r.u32()
        kw["pie_value"] = r.u32()
        kw["min_tari_value"] = r.u32()
        kw["max_tari_value"] = r.u32()
        kw["step_tari_value"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2InventoryCommand(LLRPParameter):
    """``C1G2InventoryCommand`` — LLRP TLV parameter, type 330."""

    PARAM_TYPE: ClassVar[int] = 330

    tag_inventory_state_aware: bool = False
    c1_g2_filters: list[C1G2Filter] = field(default_factory=list)
    c1_g2_rf_control: C1G2RFControl | None = None
    c1_g2_singulation_control: C1G2SingulationControl | None = None
    custom: list[CustomParameter] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.tag_inventory_state_aware), 1)
        w.bits(0, 7)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["tag_inventory_state_aware"] = bool(r.bits(1))
        r.bits(7)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2Filter(LLRPParameter):
    """``C1G2Filter`` — LLRP TLV parameter, type 331."""

    PARAM_TYPE: ClassVar[int] = 331

    t: int = 0  # enum: C1G2TruncateAction
    c1_g2_tag_inventory_mask: C1G2TagInventoryMask
    c1_g2_tag_inventory_state_aware_filter_action: C1G2TagInventoryStateAwareFilterAction | None = None
    c1_g2_tag_inventory_state_unaware_filter_action: C1G2TagInventoryStateUnawareFilterAction | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(self.t, 2)
        w.bits(0, 6)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["t"] = maybe_enum(r.bits(2), enums.C1G2TruncateAction)
        r.bits(6)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2TagInventoryMask(LLRPParameter):
    """``C1G2TagInventoryMask`` — LLRP TLV parameter, type 332."""

    PARAM_TYPE: ClassVar[int] = 332

    mb: int = 0
    pointer: int = 0
    tag_mask: BitStr = field(default_factory=BitStr)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(self.mb, 2)
        w.bits(0, 6)  # reserved
        w.u16(self.pointer)
        w.u1v(self.tag_mask)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["mb"] = r.bits(2)
        r.bits(6)  # reserved
        kw["pointer"] = r.u16()
        kw["tag_mask"] = r.u1v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2TagInventoryStateAwareFilterAction(LLRPParameter):
    """``C1G2TagInventoryStateAwareFilterAction`` — LLRP TLV parameter, type 333."""

    PARAM_TYPE: ClassVar[int] = 333

    target: int = 0  # enum: C1G2StateAwareTarget
    action: int = 0  # enum: C1G2StateAwareAction

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.target)
        w.u8(self.action)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["target"] = maybe_enum(r.u8(), enums.C1G2StateAwareTarget)
        kw["action"] = maybe_enum(r.u8(), enums.C1G2StateAwareAction)
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2TagInventoryStateUnawareFilterAction(LLRPParameter):
    """``C1G2TagInventoryStateUnawareFilterAction`` — LLRP TLV parameter, type 334."""

    PARAM_TYPE: ClassVar[int] = 334

    action: int = 0  # enum: C1G2StateUnawareAction

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.action)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["action"] = maybe_enum(r.u8(), enums.C1G2StateUnawareAction)
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2RFControl(LLRPParameter):
    """``C1G2RFControl`` — LLRP TLV parameter, type 335."""

    PARAM_TYPE: ClassVar[int] = 335

    mode_index: int = 0
    tari: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.mode_index)
        w.u16(self.tari)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["mode_index"] = r.u16()
        kw["tari"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2SingulationControl(LLRPParameter):
    """``C1G2SingulationControl`` — LLRP TLV parameter, type 336."""

    PARAM_TYPE: ClassVar[int] = 336

    session: int = 0
    tag_population: int = 0
    tag_transit_time: int = 0
    c1_g2_tag_inventory_state_aware_singulation_action: C1G2TagInventoryStateAwareSingulationAction | None = None

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(self.session, 2)
        w.bits(0, 6)  # reserved
        w.u16(self.tag_population)
        w.u32(self.tag_transit_time)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["session"] = r.bits(2)
        r.bits(6)  # reserved
        kw["tag_population"] = r.u16()
        kw["tag_transit_time"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2TagInventoryStateAwareSingulationAction(LLRPParameter):
    """``C1G2TagInventoryStateAwareSingulationAction`` — LLRP TLV parameter, type 337."""

    PARAM_TYPE: ClassVar[int] = 337

    i: bool = False  # enum: C1G2TagInventoryStateAwareI
    s: bool = False  # enum: C1G2TagInventoryStateAwareS

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.i), 1)
        w.bits(int(self.s), 1)
        w.bits(0, 6)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["i"] = bool(r.bits(1))
        kw["s"] = bool(r.bits(1))
        r.bits(6)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2TagSpec(LLRPParameter):
    """``C1G2TagSpec`` — LLRP TLV parameter, type 338."""

    PARAM_TYPE: ClassVar[int] = 338

    c1_g2_target_tags: list[C1G2TargetTag] = field(default_factory=list)


@register_parameter
@dataclass(kw_only=True)
class C1G2TargetTag(LLRPParameter):
    """``C1G2TargetTag`` — LLRP TLV parameter, type 339."""

    PARAM_TYPE: ClassVar[int] = 339

    mb: int = 0
    match: bool = False
    pointer: int = 0
    tag_mask: BitStr = field(default_factory=BitStr)
    tag_data: BitStr = field(default_factory=BitStr)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(self.mb, 2)
        w.bits(int(self.match), 1)
        w.bits(0, 5)  # reserved
        w.u16(self.pointer)
        w.u1v(self.tag_mask)
        w.u1v(self.tag_data)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["mb"] = r.bits(2)
        kw["match"] = bool(r.bits(1))
        r.bits(5)  # reserved
        kw["pointer"] = r.u16()
        kw["tag_mask"] = r.u1v()
        kw["tag_data"] = r.u1v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2Read(LLRPParameter):
    """``C1G2Read`` — LLRP TLV parameter, type 341."""

    PARAM_TYPE: ClassVar[int] = 341

    op_spec_id: int = 0
    access_password: int = 0
    mb: int = 0
    word_pointer: int = 0
    word_count: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.op_spec_id)
        w.u32(self.access_password)
        w.bits(self.mb, 2)
        w.bits(0, 6)  # reserved
        w.u16(self.word_pointer)
        w.u16(self.word_count)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["op_spec_id"] = r.u16()
        kw["access_password"] = r.u32()
        kw["mb"] = r.bits(2)
        r.bits(6)  # reserved
        kw["word_pointer"] = r.u16()
        kw["word_count"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2Write(LLRPParameter):
    """``C1G2Write`` — LLRP TLV parameter, type 342."""

    PARAM_TYPE: ClassVar[int] = 342

    op_spec_id: int = 0
    access_password: int = 0
    mb: int = 0
    word_pointer: int = 0
    write_data: list[int] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.op_spec_id)
        w.u32(self.access_password)
        w.bits(self.mb, 2)
        w.bits(0, 6)  # reserved
        w.u16(self.word_pointer)
        w.u16v(self.write_data)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["op_spec_id"] = r.u16()
        kw["access_password"] = r.u32()
        kw["mb"] = r.bits(2)
        r.bits(6)  # reserved
        kw["word_pointer"] = r.u16()
        kw["write_data"] = r.u16v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2Kill(LLRPParameter):
    """``C1G2Kill`` — LLRP TLV parameter, type 343."""

    PARAM_TYPE: ClassVar[int] = 343

    op_spec_id: int = 0
    kill_password: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.op_spec_id)
        w.u32(self.kill_password)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["op_spec_id"] = r.u16()
        kw["kill_password"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2Lock(LLRPParameter):
    """``C1G2Lock`` — LLRP TLV parameter, type 344."""

    PARAM_TYPE: ClassVar[int] = 344

    op_spec_id: int = 0
    access_password: int = 0
    c1_g2_lock_payloads: list[C1G2LockPayload] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.op_spec_id)
        w.u32(self.access_password)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["op_spec_id"] = r.u16()
        kw["access_password"] = r.u32()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2LockPayload(LLRPParameter):
    """``C1G2LockPayload`` — LLRP TLV parameter, type 345."""

    PARAM_TYPE: ClassVar[int] = 345

    privilege: int = 0  # enum: C1G2LockPrivilege
    data_field: int = 0  # enum: C1G2LockDataField

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.privilege)
        w.u8(self.data_field)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["privilege"] = maybe_enum(r.u8(), enums.C1G2LockPrivilege)
        kw["data_field"] = maybe_enum(r.u8(), enums.C1G2LockDataField)
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2BlockErase(LLRPParameter):
    """``C1G2BlockErase`` — LLRP TLV parameter, type 346."""

    PARAM_TYPE: ClassVar[int] = 346

    op_spec_id: int = 0
    access_password: int = 0
    mb: int = 0
    word_pointer: int = 0
    word_count: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.op_spec_id)
        w.u32(self.access_password)
        w.bits(self.mb, 2)
        w.bits(0, 6)  # reserved
        w.u16(self.word_pointer)
        w.u16(self.word_count)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["op_spec_id"] = r.u16()
        kw["access_password"] = r.u32()
        kw["mb"] = r.bits(2)
        r.bits(6)  # reserved
        kw["word_pointer"] = r.u16()
        kw["word_count"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2BlockWrite(LLRPParameter):
    """``C1G2BlockWrite`` — LLRP TLV parameter, type 347."""

    PARAM_TYPE: ClassVar[int] = 347

    op_spec_id: int = 0
    access_password: int = 0
    mb: int = 0
    word_pointer: int = 0
    write_data: list[int] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.op_spec_id)
        w.u32(self.access_password)
        w.bits(self.mb, 2)
        w.bits(0, 6)  # reserved
        w.u16(self.word_pointer)
        w.u16v(self.write_data)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["op_spec_id"] = r.u16()
        kw["access_password"] = r.u32()
        kw["mb"] = r.bits(2)
        r.bits(6)  # reserved
        kw["word_pointer"] = r.u16()
        kw["write_data"] = r.u16v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2EPCMemorySelector(LLRPParameter):
    """``C1G2EPCMemorySelector`` — LLRP TLV parameter, type 348."""

    PARAM_TYPE: ClassVar[int] = 348

    enable_crc: bool = False
    enable_pc_bits: bool = False

    def _encode_fields(self, w: ByteWriter) -> None:
        w.bits(int(self.enable_crc), 1)
        w.bits(int(self.enable_pc_bits), 1)
        w.bits(0, 6)  # reserved

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["enable_crc"] = bool(r.bits(1))
        kw["enable_pc_bits"] = bool(r.bits(1))
        r.bits(6)  # reserved
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2_PC(LLRPParameter):
    """``C1G2_PC`` — LLRP TV parameter, type 12."""

    PARAM_TYPE: ClassVar[int] = 12
    IS_TV: ClassVar[bool] = True

    pc_bits: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.pc_bits)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["pc_bits"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2_CRC(LLRPParameter):
    """``C1G2_CRC`` — LLRP TV parameter, type 11."""

    PARAM_TYPE: ClassVar[int] = 11
    IS_TV: ClassVar[bool] = True

    crc: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.crc)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["crc"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2SingulationDetails(LLRPParameter):
    """``C1G2SingulationDetails`` — LLRP TV parameter, type 18."""

    PARAM_TYPE: ClassVar[int] = 18
    IS_TV: ClassVar[bool] = True

    num_collision_slots: int = 0
    num_empty_slots: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u16(self.num_collision_slots)
        w.u16(self.num_empty_slots)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["num_collision_slots"] = r.u16()
        kw["num_empty_slots"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2ReadOpSpecResult(LLRPParameter):
    """``C1G2ReadOpSpecResult`` — LLRP TLV parameter, type 349."""

    PARAM_TYPE: ClassVar[int] = 349

    result: int = 0  # enum: C1G2ReadResultType
    op_spec_id: int = 0
    read_data: list[int] = field(default_factory=list)

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.result)
        w.u16(self.op_spec_id)
        w.u16v(self.read_data)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["result"] = maybe_enum(r.u8(), enums.C1G2ReadResultType)
        kw["op_spec_id"] = r.u16()
        kw["read_data"] = r.u16v()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2WriteOpSpecResult(LLRPParameter):
    """``C1G2WriteOpSpecResult`` — LLRP TLV parameter, type 350."""

    PARAM_TYPE: ClassVar[int] = 350

    result: int = 0  # enum: C1G2WriteResultType
    op_spec_id: int = 0
    num_words_written: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.result)
        w.u16(self.op_spec_id)
        w.u16(self.num_words_written)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["result"] = maybe_enum(r.u8(), enums.C1G2WriteResultType)
        kw["op_spec_id"] = r.u16()
        kw["num_words_written"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2KillOpSpecResult(LLRPParameter):
    """``C1G2KillOpSpecResult`` — LLRP TLV parameter, type 351."""

    PARAM_TYPE: ClassVar[int] = 351

    result: int = 0  # enum: C1G2KillResultType
    op_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.result)
        w.u16(self.op_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["result"] = maybe_enum(r.u8(), enums.C1G2KillResultType)
        kw["op_spec_id"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2LockOpSpecResult(LLRPParameter):
    """``C1G2LockOpSpecResult`` — LLRP TLV parameter, type 352."""

    PARAM_TYPE: ClassVar[int] = 352

    result: int = 0  # enum: C1G2LockResultType
    op_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.result)
        w.u16(self.op_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["result"] = maybe_enum(r.u8(), enums.C1G2LockResultType)
        kw["op_spec_id"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2BlockEraseOpSpecResult(LLRPParameter):
    """``C1G2BlockEraseOpSpecResult`` — LLRP TLV parameter, type 353."""

    PARAM_TYPE: ClassVar[int] = 353

    result: int = 0  # enum: C1G2BlockEraseResultType
    op_spec_id: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.result)
        w.u16(self.op_spec_id)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["result"] = maybe_enum(r.u8(), enums.C1G2BlockEraseResultType)
        kw["op_spec_id"] = r.u16()
        return kw


@register_parameter
@dataclass(kw_only=True)
class C1G2BlockWriteOpSpecResult(LLRPParameter):
    """``C1G2BlockWriteOpSpecResult`` — LLRP TLV parameter, type 354."""

    PARAM_TYPE: ClassVar[int] = 354

    result: int = 0  # enum: C1G2BlockWriteResultType
    op_spec_id: int = 0
    num_words_written: int = 0

    def _encode_fields(self, w: ByteWriter) -> None:
        w.u8(self.result)
        w.u16(self.op_spec_id)
        w.u16(self.num_words_written)

    @classmethod
    def _decode_fields(cls, r: ByteReader, end: int) -> dict[str, Any]:
        kw: dict[str, Any] = {}
        kw["result"] = maybe_enum(r.u8(), enums.C1G2BlockWriteResultType)
        kw["op_spec_id"] = r.u16()
        kw["num_words_written"] = r.u16()
        return kw


# --- containment slots (assigned after all classes exist) ---

GeneralDeviceCapabilities._SLOTS = (
    ParamSlot("receive_sensitivity_table_entrys", (ReceiveSensitivityTableEntry,), 1, True),
    ParamSlot("per_antenna_receive_sensitivity_ranges", (PerAntennaReceiveSensitivityRange,), 0, True),
    ParamSlot("gpio_capabilities", (GPIOCapabilities,), 1, False),
    ParamSlot("per_antenna_air_protocols", (PerAntennaAirProtocol,), 1, True),
)
RegulatoryCapabilities._SLOTS = (
    ParamSlot("uhf_band_capabilities", (UHFBandCapabilities,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
UHFBandCapabilities._SLOTS = (
    ParamSlot("transmit_power_level_table_entrys", (TransmitPowerLevelTableEntry,), 1, True),
    ParamSlot("frequency_information", (FrequencyInformation,), 1, False),
    ParamSlot("air_protocol_uhfrf_mode_tables", (C1G2UHFRFModeTable,), 1, True),
)
FrequencyInformation._SLOTS = (
    ParamSlot("frequency_hop_tables", (FrequencyHopTable,), 0, True),
    ParamSlot("fixed_frequency_table", (FixedFrequencyTable,), 0, False),
)
ROSpec._SLOTS = (
    ParamSlot("ro_boundary_spec", (ROBoundarySpec,), 1, False),
    ParamSlot("spec_parameters", (AISpec, RFSurveySpec, CustomParameter), 1, True),
    ParamSlot("ro_report_spec", (ROReportSpec,), 0, False),
)
ROBoundarySpec._SLOTS = (
    ParamSlot("ro_spec_start_trigger", (ROSpecStartTrigger,), 1, False),
    ParamSlot("ro_spec_stop_trigger", (ROSpecStopTrigger,), 1, False),
)
ROSpecStartTrigger._SLOTS = (
    ParamSlot("periodic_trigger_value", (PeriodicTriggerValue,), 0, False),
    ParamSlot("gpi_trigger_value", (GPITriggerValue,), 0, False),
)
PeriodicTriggerValue._SLOTS = (
    ParamSlot("utc_timestamp", (UTCTimestamp,), 0, False),
)
ROSpecStopTrigger._SLOTS = (
    ParamSlot("gpi_trigger_value", (GPITriggerValue,), 0, False),
)
AISpec._SLOTS = (
    ParamSlot("ai_spec_stop_trigger", (AISpecStopTrigger,), 1, False),
    ParamSlot("inventory_parameter_specs", (InventoryParameterSpec,), 1, True),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
AISpecStopTrigger._SLOTS = (
    ParamSlot("gpi_trigger_value", (GPITriggerValue,), 0, False),
    ParamSlot("tag_observation_trigger", (TagObservationTrigger,), 0, False),
)
InventoryParameterSpec._SLOTS = (
    ParamSlot("antenna_configurations", (AntennaConfiguration,), 0, True),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
RFSurveySpec._SLOTS = (
    ParamSlot("rf_survey_spec_stop_trigger", (RFSurveySpecStopTrigger,), 1, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
AccessSpec._SLOTS = (
    ParamSlot("access_spec_stop_trigger", (AccessSpecStopTrigger,), 1, False),
    ParamSlot("access_command", (AccessCommand,), 1, False),
    ParamSlot("access_report_spec", (AccessReportSpec,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
AccessCommand._SLOTS = (
    ParamSlot("air_protocol_tag_spec", (C1G2TagSpec,), 1, False),
    ParamSlot("access_command_op_specs", (C1G2Read, C1G2Write, C1G2Kill, C1G2Lock, C1G2BlockErase, C1G2BlockWrite), 1, True),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
AntennaConfiguration._SLOTS = (
    ParamSlot("rf_receiver", (RFReceiver,), 0, False),
    ParamSlot("rf_transmitter", (RFTransmitter,), 0, False),
    ParamSlot("air_protocol_inventory_command_settings", (C1G2InventoryCommand,), 0, True),
)
ROReportSpec._SLOTS = (
    ParamSlot("tag_report_content_selector", (TagReportContentSelector,), 1, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
TagReportContentSelector._SLOTS = (
    ParamSlot("air_protocol_epc_memory_selectors", (C1G2EPCMemorySelector,), 0, True),
)
TagReportData._SLOTS = (
    ParamSlot("epc_parameter", (EPCData, EPC_96), 1, False),
    ParamSlot("ro_spec_id", (ROSpecID,), 0, False),
    ParamSlot("spec_index", (SpecIndex,), 0, False),
    ParamSlot("inventory_parameter_spec_id", (InventoryParameterSpecID,), 0, False),
    ParamSlot("antenna_id", (AntennaID,), 0, False),
    ParamSlot("peak_rssi", (PeakRSSI,), 0, False),
    ParamSlot("channel_index", (ChannelIndex,), 0, False),
    ParamSlot("first_seen_timestamp_utc", (FirstSeenTimestampUTC,), 0, False),
    ParamSlot("first_seen_timestamp_uptime", (FirstSeenTimestampUptime,), 0, False),
    ParamSlot("last_seen_timestamp_utc", (LastSeenTimestampUTC,), 0, False),
    ParamSlot("last_seen_timestamp_uptime", (LastSeenTimestampUptime,), 0, False),
    ParamSlot("tag_seen_count", (TagSeenCount,), 0, False),
    ParamSlot("air_protocol_tag_datas", (C1G2_PC, C1G2_CRC), 0, True),
    ParamSlot("access_spec_id", (AccessSpecID,), 0, False),
    ParamSlot("access_command_op_spec_results", (C1G2ReadOpSpecResult, C1G2WriteOpSpecResult, C1G2KillOpSpecResult, C1G2LockOpSpecResult, C1G2BlockEraseOpSpecResult, C1G2BlockWriteOpSpecResult), 0, True),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
RFSurveyReportData._SLOTS = (
    ParamSlot("ro_spec_id", (ROSpecID,), 0, False),
    ParamSlot("spec_index", (SpecIndex,), 0, False),
    ParamSlot("frequency_rssi_level_entrys", (FrequencyRSSILevelEntry,), 1, True),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
FrequencyRSSILevelEntry._SLOTS = (
    ParamSlot("timestamp", (UTCTimestamp, Uptime), 1, False),
)
ReaderEventNotificationSpec._SLOTS = (
    ParamSlot("event_notification_states", (EventNotificationState,), 1, True),
)
ReaderEventNotificationData._SLOTS = (
    ParamSlot("timestamp", (UTCTimestamp, Uptime), 1, False),
    ParamSlot("hopping_event", (HoppingEvent,), 0, False),
    ParamSlot("gpi_event", (GPIEvent,), 0, False),
    ParamSlot("ro_spec_event", (ROSpecEvent,), 0, False),
    ParamSlot("report_buffer_level_warning_event", (ReportBufferLevelWarningEvent,), 0, False),
    ParamSlot("report_buffer_overflow_error_event", (ReportBufferOverflowErrorEvent,), 0, False),
    ParamSlot("reader_exception_event", (ReaderExceptionEvent,), 0, False),
    ParamSlot("rf_survey_event", (RFSurveyEvent,), 0, False),
    ParamSlot("ai_spec_event", (AISpecEvent,), 0, False),
    ParamSlot("antenna_event", (AntennaEvent,), 0, False),
    ParamSlot("connection_attempt_event", (ConnectionAttemptEvent,), 0, False),
    ParamSlot("connection_close_event", (ConnectionCloseEvent,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
ReaderExceptionEvent._SLOTS = (
    ParamSlot("ro_spec_id", (ROSpecID,), 0, False),
    ParamSlot("spec_index", (SpecIndex,), 0, False),
    ParamSlot("inventory_parameter_spec_id", (InventoryParameterSpecID,), 0, False),
    ParamSlot("antenna_id", (AntennaID,), 0, False),
    ParamSlot("access_spec_id", (AccessSpecID,), 0, False),
    ParamSlot("op_spec_id", (OpSpecID,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
AISpecEvent._SLOTS = (
    ParamSlot("air_protocol_singulation_details", (C1G2SingulationDetails,), 0, False),
)
LLRPStatus._SLOTS = (
    ParamSlot("field_error", (FieldError,), 0, False),
    ParamSlot("parameter_error", (ParameterError,), 0, False),
)
ParameterError._SLOTS = (
    ParamSlot("field_error", (FieldError,), 0, False),
    ParamSlot("parameter_error", (ParameterError,), 0, False),
)
C1G2UHFRFModeTable._SLOTS = (
    ParamSlot("c1_g2_uhfrf_mode_table_entrys", (C1G2UHFRFModeTableEntry,), 1, True),
)
C1G2InventoryCommand._SLOTS = (
    ParamSlot("c1_g2_filters", (C1G2Filter,), 0, True),
    ParamSlot("c1_g2_rf_control", (C1G2RFControl,), 0, False),
    ParamSlot("c1_g2_singulation_control", (C1G2SingulationControl,), 0, False),
    ParamSlot("custom", (CustomParameter,), 0, True),
)
C1G2Filter._SLOTS = (
    ParamSlot("c1_g2_tag_inventory_mask", (C1G2TagInventoryMask,), 1, False),
    ParamSlot("c1_g2_tag_inventory_state_aware_filter_action", (C1G2TagInventoryStateAwareFilterAction,), 0, False),
    ParamSlot("c1_g2_tag_inventory_state_unaware_filter_action", (C1G2TagInventoryStateUnawareFilterAction,), 0, False),
)
C1G2SingulationControl._SLOTS = (
    ParamSlot("c1_g2_tag_inventory_state_aware_singulation_action", (C1G2TagInventoryStateAwareSingulationAction,), 0, False),
)
C1G2TagSpec._SLOTS = (
    ParamSlot("c1_g2_target_tags", (C1G2TargetTag,), 1, True),
)
C1G2Lock._SLOTS = (
    ParamSlot("c1_g2_lock_payloads", (C1G2LockPayload,), 1, True),
)
